[package]
name = "technology_6a_desktop"
version = "0.1.0"
description = "Technology 6A Vocabulary desktop app"
authors = ["Academia Internacional de David"]
edition = "2021"

[lib]
name = "technology_6a_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
