import '../css/inter-latin.css';
import {
    createIcons as createLucideIcons,
    Activity,
    Archive,
    ArrowLeft,
    ArrowRight,
    BadgeCheck,
    BookOpen,
    BookOpenCheck,
    CalendarCheck,
    CalendarDays,
    CalendarRange,
    ChartNoAxesCombined,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    CircleCheck,
    CircleHelp,
    CircleX,
    ClipboardCheck,
    CloudUpload,
    Coins,
    Compass,
    Copy,
    CopyPlus,
    Download,
    Eye,
    EyeOff,
    FileDown,
    FilePlus,
    FileText,
    FileUp,
    FolderOpen,
    Gamepad2,
    GraduationCap,
    Grid3X3,
    Info,
    Layers,
    Layers3,
    LayoutDashboard,
    LayoutGrid,
    Lightbulb,
    List,
    ListFilter,
    LoaderCircle,
    LogOut,
    Menu,
    MessageCircleQuestion,
    MessagesSquare,
    Pencil,
    Plus,
    Presentation,
    Puzzle,
    RefreshCw,
    Repeat2,
    RotateCcw,
    ScanFace,
    Save,
    Search,
    Send,
    Settings,
    SlidersHorizontal,
    Sparkles,
    Shuffle,
    Table,
    TextCursorInput,
    Timer,
    Trash2,
    TriangleAlert,
    Upload,
    User,
    UserPlus,
    Users
} from 'lucide';

const icons = {
    Activity,
    Archive,
    ArrowLeft,
    ArrowRight,
    BadgeCheck,
    BookOpen,
    BookOpenCheck,
    CalendarCheck,
    CalendarDays,
    CalendarRange,
    ChartNoAxesCombined,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    CircleCheck,
    CircleHelp,
    CircleX,
    ClipboardCheck,
    CloudUpload,
    Coins,
    Compass,
    Copy,
    CopyPlus,
    Download,
    Eye,
    EyeOff,
    FileDown,
    FilePlus,
    FileText,
    FileUp,
    FolderOpen,
    Gamepad2,
    GraduationCap,
    Grid3X3,
    Info,
    Layers,
    Layers3,
    LayoutDashboard,
    LayoutGrid,
    Lightbulb,
    List,
    ListFilter,
    LoaderCircle,
    LogOut,
    Menu,
    MessageCircleQuestion,
    MessagesSquare,
    Pencil,
    Plus,
    Presentation,
    Puzzle,
    RefreshCw,
    Repeat2,
    RotateCcw,
    ScanFace,
    Save,
    Search,
    Send,
    Settings,
    SlidersHorizontal,
    Sparkles,
    Shuffle,
    Table,
    TextCursorInput,
    Timer,
    Trash2,
    TriangleAlert,
    Upload,
    User,
    UserPlus,
    Users
};

function createIcons(options = {}) {
    return createLucideIcons({
        icons,
        ...options
    });
}

window.lucide = {
    ...(window.lucide || {}),
    createIcons,
    icons
};

function hydrateIcons() {
    createIcons();
}

if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', hydrateIcons, { once: true });
} else {
    hydrateIcons();
}
