-- Grade 9 app activities from the monthly planning.
-- Grade 9 is secondary: formal records represent non-Word-Hunt daily grades,
-- appreciation grades, and exam project evidence. Formative records replace
-- paper-style practice, planning sheets, checks, diagrams, logs, and reflections.

with grade9_raw_activities as (
    select *
    from jsonb_to_recordset($grade9_app_activities$
[
  {
    "id": "grade9_t1_daily_2_button_toggle_practical",
    "title": "G9 T1 Daily Grade 2 - Button Toggle Practical Check",
    "class_slot": "March Week 4, 90-minute class",
    "description": "Students submit evidence for a button-input LED system and explain input, output, state, condition, and toggle behavior.",
    "activity_type": "external-artifact",
    "assessment_purpose": "formal",
    "estimated_minutes": 35,
    "template_id": "project-evidence",
    "evidence_mode": "either",
    "teacher_note": "Use for Daily Grade #2 after the button state practice.",
    "student_instructions": "Submit a photo, screenshot, code file link, or short video evidence of your button-input LED system and complete the checklist.",
    "student_output": "Button-toggle evidence, two test cases, and state-change explanation.",
    "materials": "Arduino/Freenove kit, breadboard, LED, resistor, button, code, and screenshot or photo tool.",
    "checklist": [{"id":"button_input","text":"The system uses a button as input.","required":true},{"id":"led_output","text":"The system controls one LED output.","required":true},{"id":"toggle","text":"Each press changes the LED state from off to on or on to off.","required":true},{"id":"tests","text":"I included two test cases or observations.","required":true}],
    "reflections": [{"id":"state","prompt":"Explain why the state changes when the button is pressed.","required":true},{"id":"issue","prompt":"What wiring or code issue did you check?","required":true}]
  },
  {
    "id": "grade9_t1_daily_3_sensor_threshold_rgb_check",
    "title": "G9 T1 Daily Grade 3 - Sensor Threshold and RGB Check",
    "class_slot": "April Week 6, 90-minute class",
    "description": "Students complete a quiz-style sensor threshold check and explain RGB color states using reading evidence.",
    "activity_type": "structured-response",
    "assessment_purpose": "formal",
    "estimated_minutes": 30,
    "template_id": "worksheet",
    "teacher_note": "Use for Daily Grade #3 during the sensor and RGB lesson.",
    "student_instructions": "Complete the threshold check, choose a reliable threshold, predict each output, and explain the RGB state choices.",
    "student_output": "Threshold table, rule explanation, and RGB state justification.",
    "materials": "Sensor notes, sample readings, RGB state notes, and class examples.",
    "fields": [{"id":"readings","type":"table-grid","prompt":"Complete the sensor threshold check for 6 readings.","rows":[{"id":"r1","text":"Reading 1"},{"id":"r2","text":"Reading 2"},{"id":"r3","text":"Reading 3"},{"id":"r4","text":"Reading 4"},{"id":"r5","text":"Reading 5"},{"id":"r6","text":"Reading 6"}],"columns":[{"id":"value","text":"Reading value"},{"id":"expected","text":"Expected output"},{"id":"reason","text":"Reason"}]},{"id":"threshold","type":"short-text","prompt":"What threshold did you choose?"},{"id":"rule","type":"long-text","prompt":"Explain the threshold rule in two sentences."},{"id":"rgb_states","type":"table-grid","prompt":"Plan the RGB state colors.","rows":[{"id":"ready","text":"Ready"},{"id":"active","text":"Active"},{"id":"warning","text":"Warning"},{"id":"error","text":"Error"}],"columns":[{"id":"color","text":"Color"},{"id":"reason","text":"Why it matches the state"}]}]
  },
  {
    "id": "grade9_t1_daily_4_state_logic_prototype_log",
    "title": "G9 T1 Daily Grade 4 - State Logic Chart and Prototype Log",
    "class_slot": "April Week 8, 90-minute class",
    "description": "Students create a state logic chart, combine at least one input and two outputs, and record two evidence-based improvements.",
    "activity_type": "structured-response",
    "assessment_purpose": "formal",
    "estimated_minutes": 35,
    "template_id": "worksheet",
    "teacher_note": "Use for Daily Grade #4 while students build the integrated input-output prototype.",
    "student_instructions": "Complete the state logic chart, record two prototype tests, and explain two improvements supported by evidence.",
    "student_output": "State logic chart, prototype test notes, and improvement log.",
    "materials": "Arduino/Freenove kit, buttons, sensors, RGB LED or other outputs, state chart, and project log.",
    "fields": [{"id":"states","type":"table-grid","prompt":"Complete the 4-state logic chart.","rows":[{"id":"ready","text":"Ready"},{"id":"active","text":"Active"},{"id":"warning","text":"Warning"},{"id":"error","text":"Error"}],"columns":[{"id":"trigger","text":"Input trigger"},{"id":"response","text":"Output response"},{"id":"explanation","text":"Explanation"}]},{"id":"tests","type":"table-grid","prompt":"Record two prototype tests.","rows":[{"id":"test1","text":"Test 1"},{"id":"test2","text":"Test 2"}],"columns":[{"id":"condition","text":"Input/condition"},{"id":"expected","text":"Expected result"},{"id":"actual","text":"Actual result"}]},{"id":"improvements","type":"long-text","prompt":"Describe two evidence-based improvements."}]
  },
  {
    "id": "grade9_t1_daily_5_robotics_design_plan",
    "title": "G9 T1 Daily Grade 5 - Robotics Design Plan",
    "class_slot": "May Week 9, 90-minute class",
    "description": "Students prepare the robotics project plan with goal, inputs, outputs, state chart, components, risk, and test cases.",
    "activity_type": "structured-response",
    "assessment_purpose": "formal",
    "estimated_minutes": 35,
    "template_id": "worksheet",
    "teacher_note": "Use for Daily Grade #5 before the robotics exam project begins.",
    "student_instructions": "Complete the robotics design plan before building the exam project.",
    "student_output": "Robotics design plan and one evidence-based improvement.",
    "materials": "Project rubric, planning sheet, component notes, and Arduino/Freenove kit.",
    "fields": [{"id":"goal","type":"long-text","prompt":"What is the robot goal?"},{"id":"inputs_outputs","type":"table-grid","prompt":"Plan the input-output system.","rows":[{"id":"input1","text":"Input or control 1"},{"id":"input2","text":"Input or control 2"},{"id":"output1","text":"Output 1"},{"id":"output2","text":"Output 2"}],"columns":[{"id":"part","text":"Part/component"},{"id":"behavior","text":"Expected behavior"}]},{"id":"state_chart","type":"long-text","prompt":"Describe or outline the state chart."},{"id":"risk","type":"short-text","prompt":"What is one project risk?"},{"id":"tests","type":"table-grid","prompt":"Write 3 test cases.","rows":[{"id":"test1","text":"Test case 1"},{"id":"test2","text":"Test case 2"},{"id":"test3","text":"Test case 3"}],"columns":[{"id":"condition","text":"Condition/input"},{"id":"expected","text":"Expected output"}]}]
  },
  {
    "id": "grade9_t1_appreciation_1_lab_safety_responsibility",
    "title": "G9 T1 Appreciation Grade 1 - Lab Safety and Responsibility",
    "class_slot": "March Week 3, 90-minute class",
    "description": "Students complete a lab safety and responsibility checklist and record fix evidence from LED testing.",
    "activity_type": "structured-response",
    "assessment_purpose": "formal",
    "estimated_minutes": 12,
    "template_id": "checklist",
    "teacher_note": "Use for Appreciation Grade #1 during mini LED control practice.",
    "student_instructions": "Complete the safety checklist and describe one fix you tested during the LED control activity.",
    "student_output": "Safety checklist and fix evidence note.",
    "materials": "Lab safety checklist, LED circuit, test notes, and classroom materials.",
    "fields": [{"id":"checklist","type":"checklist","prompt":"Lab safety and responsibility checklist","items":[{"id":"prepared","text":"I prepared materials and followed directions."},{"id":"careful","text":"I handled parts carefully."},{"id":"power","text":"I connected power only when ready to test."},{"id":"listening","text":"I listened during testing and cleanup."},{"id":"persistence","text":"I showed persistence when testing or fixing."}]},{"id":"fix","type":"long-text","prompt":"What issue did you find, and what evidence shows the fix worked?"}]
  },
  {
    "id": "grade9_t1_appreciation_2_teamwork_feedback",
    "title": "G9 T1 Appreciation Grade 2 - Teamwork and Feedback",
    "class_slot": "April Week 7, 90-minute class",
    "description": "Students reflect on communication, shared responsibility, respectful testing, organization, and response to feedback.",
    "activity_type": "structured-response",
    "assessment_purpose": "formal",
    "estimated_minutes": 12,
    "template_id": "reflection",
    "teacher_note": "Use for Appreciation Grade #2 while students improve the light or sound system.",
    "student_instructions": "Complete the teamwork checklist and write one change made because of feedback.",
    "student_output": "Teamwork checklist and feedback response.",
    "materials": "Team roles, project evidence, feedback notes, and checklist.",
    "fields": [{"id":"teamwork","type":"checklist","prompt":"Teamwork and feedback checklist","items":[{"id":"communication","text":"I communicated clearly with my team."},{"id":"shared","text":"I shared responsibility for the task."},{"id":"testing","text":"I tested respectfully and safely."},{"id":"organization","text":"I kept evidence organized."},{"id":"feedback","text":"I responded to feedback with an improvement."}]},{"id":"change","type":"long-text","prompt":"What feedback did you receive, and what did you change?"}]
  },
  {
    "id": "grade9_t1_exam_robotics_project_presentation",
    "title": "G9 T1 Exam Project - Robotics Project Presentation",
    "class_slot": "May Weeks 10-12 exam project",
    "description": "Students submit final robotics project evidence with goal, inputs, outputs, state logic, testing evidence, reliability, improvement, and reflection.",
    "activity_type": "external-artifact",
    "assessment_purpose": "formal",
    "estimated_minutes": 90,
    "template_id": "project-evidence",
    "evidence_mode": "either",
    "teacher_note": "Use as the exam project evidence wrapper for the robotics project.",
    "student_instructions": "Submit project evidence from the final robotics demonstration and complete the project reflection prompts.",
    "student_output": "Robotics project evidence, project log, and reflection.",
    "materials": "Robotics prototype, code, project log, screenshots/photos, test table, and rubric.",
    "checklist": [{"id":"goal","text":"The evidence states the robot goal.","required":true},{"id":"inputs_outputs","text":"The evidence identifies inputs, outputs, and state logic.","required":true},{"id":"testing","text":"The evidence includes testing or reliability notes.","required":true},{"id":"improvement","text":"The evidence explains one improvement.","required":true},{"id":"reflection","text":"The final reflection is complete.","required":true}],
    "reflections": [{"id":"logic","prompt":"How do the inputs, logic, and outputs work together?","required":true},{"id":"reliability","prompt":"What evidence shows how reliable the project is?","required":true},{"id":"next","prompt":"What would you improve next?","required":true}]
  },
  {
    "id": "grade9_t2_daily_2_loop_debugging_check",
    "title": "G9 T2 Daily Grade 2 - Loop Debugging Check",
    "class_slot": "June Week 3, 90-minute class",
    "description": "Students correct a Python loop program with four marked issues and explain each fix.",
    "activity_type": "structured-response",
    "assessment_purpose": "formal",
    "estimated_minutes": 30,
    "template_id": "worksheet",
    "teacher_note": "Use for Daily Grade #2 during the loops and strings lesson.",
    "student_instructions": "Correct the loop program, submit the corrected code/output, and explain each fix.",
    "student_output": "Corrected code, output, and four fix explanations.",
    "materials": "Python editor, loop notes, broken code sample, and class examples.",
    "fields": [{"id":"corrected_code","type":"long-text","prompt":"Paste or summarize the corrected code."},{"id":"output","type":"long-text","prompt":"What output did the corrected program produce?"},{"id":"fixes","type":"table-grid","prompt":"Explain the four fixes.","rows":[{"id":"fix1","text":"Fix 1"},{"id":"fix2","text":"Fix 2"},{"id":"fix3","text":"Fix 3"},{"id":"fix4","text":"Fix 4"}],"columns":[{"id":"issue","text":"Original issue"},{"id":"correction","text":"Correction"},{"id":"why","text":"Why it works"}]}]
  },
  {
    "id": "grade9_t2_daily_3_data_collection_plan",
    "title": "G9 T2 Daily Grade 3 - Data Collection Plan and Table",
    "class_slot": "July Week 5, 90-minute class",
    "description": "Students create a data collection plan and organize a small dataset with clear headings, units, categories, and privacy rule.",
    "activity_type": "structured-response",
    "assessment_purpose": "formal",
    "estimated_minutes": 35,
    "template_id": "worksheet",
    "teacher_note": "Use for Daily Grade #3 during data collection and organization.",
    "student_instructions": "Complete the data collection plan, list survey or measurement items, and describe how the dataset will be organized.",
    "student_output": "Data question, collection plan, privacy rule, and organized table plan.",
    "materials": "Dataset or survey plan, Google Classroom, spreadsheet tool, and privacy notes.",
    "fields": [{"id":"question","type":"long-text","prompt":"Write the measurable data question."},{"id":"items","type":"table-grid","prompt":"Plan 5 survey or measurement items.","rows":[{"id":"item1","text":"Item 1"},{"id":"item2","text":"Item 2"},{"id":"item3","text":"Item 3"},{"id":"item4","text":"Item 4"},{"id":"item5","text":"Item 5"}],"columns":[{"id":"wording","text":"Question/item wording"},{"id":"data_type","text":"Expected data type"},{"id":"unit_category","text":"Unit or category"}]},{"id":"method","type":"short-text","prompt":"How will you collect or enter the data?"},{"id":"privacy","type":"long-text","prompt":"What privacy rule will you follow?"},{"id":"quality","type":"long-text","prompt":"List two data quality issues you checked."}]
  },
  {
    "id": "grade9_t2_daily_4_chart_interpretation_check",
    "title": "G9 T2 Daily Grade 4 - Chart and Interpretation Check",
    "class_slot": "July Week 7, 90-minute class",
    "description": "Students create one chart and write interpretation sentences for pattern, comparison, outlier or limitation, and conclusion.",
    "activity_type": "spreadsheet-table",
    "assessment_purpose": "formal",
    "estimated_minutes": 35,
    "template_id": "data-table",
    "teacher_note": "Use for Daily Grade #4 during charts, patterns, correlation, and outliers.",
    "student_instructions": "Enter or summarize the dataset for your chart, then write the required interpretation sentences.",
    "student_output": "Chart data table, interpretation sentences, and careful conclusion.",
    "materials": "Dataset, chart tool, notes about patterns, outliers, and conclusions.",
    "columns": [{"id":"category","title":"Category or Item","type":"text","width":170},{"id":"value","title":"Value","type":"number","width":110},{"id":"note","title":"Pattern/Outlier Note","type":"text","width":220}],
    "min_rows": 5,
    "max_rows": 15,
    "chart": {"enabled":true,"type":"bar","labelColumnId":"category","valueColumnId":"value"},
    "reflections": [{"id":"pattern","prompt":"Write one pattern sentence.","required":true},{"id":"comparison","prompt":"Write one comparison sentence.","required":true},{"id":"outlier","prompt":"Write one outlier or limitation sentence.","required":true},{"id":"conclusion","prompt":"Write one careful conclusion.","required":true}]
  },
  {
    "id": "grade9_t2_daily_5_data_report_draft",
    "title": "G9 T2 Daily Grade 5 - Data Report Draft",
    "class_slot": "July Week 8, 90-minute class",
    "description": "Students draft a one-page data report with title, question, chart, evidence statements, limitation, recommendation, and feedback note.",
    "activity_type": "structured-response",
    "assessment_purpose": "formal",
    "estimated_minutes": 35,
    "template_id": "worksheet",
    "teacher_note": "Use for Daily Grade #5 before the data exam project begins.",
    "student_instructions": "Complete the data report draft and record feedback from the 30-second understanding test.",
    "student_output": "One-page data report draft and feedback response.",
    "materials": "Clean dataset, chart, report draft, prototype idea, and feedback notes.",
    "fields": [{"id":"title","type":"short-text","prompt":"Report title"},{"id":"question","type":"long-text","prompt":"Data question"},{"id":"evidence","type":"table-grid","prompt":"Write 3 evidence statements.","rows":[{"id":"e1","text":"Evidence 1"},{"id":"e2","text":"Evidence 2"},{"id":"e3","text":"Evidence 3"}],"columns":[{"id":"statement","text":"Evidence statement"}]},{"id":"limitation","type":"long-text","prompt":"What is one limitation?"},{"id":"recommendation","type":"long-text","prompt":"What recommendation follows from the evidence?"},{"id":"feedback","type":"long-text","prompt":"What feedback did you receive, and what will you change?"}]
  },
  {
    "id": "grade9_t2_appreciation_1_data_teamwork_checklist",
    "title": "G9 T2 Appreciation Grade 1 - Data Teamwork Checklist",
    "class_slot": "July Week 6, 90-minute class",
    "description": "Students complete a collaboration checklist and record a data cleaning change log.",
    "activity_type": "structured-response",
    "assessment_purpose": "formal",
    "estimated_minutes": 12,
    "template_id": "checklist",
    "teacher_note": "Use for Appreciation Grade #1 while students clean the assigned dataset.",
    "student_instructions": "Complete the collaboration checklist and record at least three cleaned values.",
    "student_output": "Data teamwork checklist and change log.",
    "materials": "Messy dataset, cleaning notes, Tinkercad model evidence when used, and checklist.",
    "fields": [{"id":"checklist","type":"checklist","prompt":"Pair programming and data teamwork checklist","items":[{"id":"responsibility","text":"I worked responsibly with the dataset."},{"id":"respect","text":"I communicated respectfully."},{"id":"shared","text":"I shared work fairly."},{"id":"care","text":"I handled data carefully."},{"id":"persistence","text":"I showed persistence during cleaning."}]},{"id":"changes","type":"table-grid","prompt":"Record at least 3 cleaned values.","rows":[{"id":"c1","text":"Change 1"},{"id":"c2","text":"Change 2"},{"id":"c3","text":"Change 3"}],"columns":[{"id":"before","text":"Before"},{"id":"after","text":"After"},{"id":"reason","text":"Reason"}]}]
  },
  {
    "id": "grade9_t2_appreciation_2_data_project_readiness",
    "title": "G9 T2 Appreciation Grade 2 - Data Project Readiness Reflection",
    "class_slot": "August Week 9, 90-minute class",
    "description": "Students reflect on effort, organization, responsible data use, deadlines, feedback, and data project readiness.",
    "activity_type": "structured-response",
    "assessment_purpose": "formal",
    "estimated_minutes": 12,
    "template_id": "reflection",
    "teacher_note": "Use for Appreciation Grade #2 during data project planning.",
    "student_instructions": "Complete the self-reflection and project readiness notes before the exam project begins.",
    "student_output": "Readiness reflection and data exam project plan notes.",
    "materials": "Data table, chart, conclusion, project rubric, saved files, and feedback notes.",
    "fields": [{"id":"effort","type":"rating-scale","prompt":"Rate your effort from 1 to 5."},{"id":"organization","type":"long-text","prompt":"What evidence shows your files and data are organized?"},{"id":"responsible_data","type":"long-text","prompt":"How did you use data responsibly?"},{"id":"feedback","type":"long-text","prompt":"How did you respond to feedback?"},{"id":"resource","type":"short-text","prompt":"What resource is still needed, if any?"}]
  },
  {
    "id": "grade9_t2_exam_data_project_presentation",
    "title": "G9 T2 Exam Project - Data Project Presentation",
    "class_slot": "August Weeks 10-12 exam project",
    "description": "Students submit the final data product with question, method, clean data, chart, conclusion, limitation, recommendation, final product, and reflection.",
    "activity_type": "external-artifact",
    "assessment_purpose": "formal",
    "estimated_minutes": 90,
    "template_id": "project-evidence",
    "evidence_mode": "either",
    "teacher_note": "Use as the exam project evidence wrapper for the data project.",
    "student_instructions": "Submit the final data project link or screenshot evidence and complete the project reflection prompts.",
    "student_output": "Final data product, dataset evidence, presentation evidence, and reflection.",
    "materials": "Clean dataset, chart, report/dashboard/infographic, Tinkercad model if used, and rubric.",
    "checklist": [{"id":"question","text":"The project includes a clear data question and method.","required":true},{"id":"clean_data","text":"The project includes clean data or dataset evidence.","required":true},{"id":"chart","text":"The project includes at least one chart or visualization.","required":true},{"id":"conclusion","text":"The conclusion matches the evidence and includes a limitation.","required":true},{"id":"product","text":"The final product and reflection are submitted.","required":true}],
    "reflections": [{"id":"finding","prompt":"What is the main finding from your data?","required":true},{"id":"limitation","prompt":"What limitation should the audience remember?","required":true},{"id":"revision","prompt":"What revision improved your final product?","required":true}]
  },
  {
    "id": "grade9_t3_daily_2_image_sound_representation_check",
    "title": "G9 T3 Daily Grade 2 - Image and Sound Representation Check",
    "class_slot": "September Week 2, 90-minute class",
    "description": "Students answer image and sound representation questions and compare sample rates or file settings.",
    "activity_type": "structured-response",
    "assessment_purpose": "formal",
    "estimated_minutes": 30,
    "template_id": "worksheet",
    "teacher_note": "Use for Daily Grade #2 during the Sonic Playground lesson.",
    "student_instructions": "Complete the image and sound representation check, then summarize the sound evidence table.",
    "student_output": "Representation check and sound setting comparison.",
    "materials": "Class notes, pixel/image examples, Audacity or approved web audio tool, headphones when available.",
    "fields": [{"id":"image","type":"table-grid","prompt":"Answer the image representation items.","rows":[{"id":"pixel","text":"Pixel"},{"id":"resolution","text":"Resolution"},{"id":"color_depth","text":"Color depth"},{"id":"rgb","text":"RGB"},{"id":"compression","text":"Compression"}],"columns":[{"id":"answer","text":"Answer or calculation"},{"id":"evidence","text":"Evidence/reason"}]},{"id":"sound","type":"table-grid","prompt":"Answer the sound representation items.","rows":[{"id":"sample_rate","text":"Sample rate"},{"id":"sample_size","text":"Sample size"},{"id":"microphone","text":"Microphone"},{"id":"speaker","text":"Speaker"},{"id":"file_size","text":"File size/quality"}],"columns":[{"id":"answer","text":"Answer or calculation"},{"id":"evidence","text":"Evidence/reason"}]},{"id":"comparison","type":"long-text","prompt":"What changed when you compared two sample rates or file settings?"}]
  },
  {
    "id": "grade9_t3_daily_3_cyber_security_scenario_quiz",
    "title": "G9 T3 Daily Grade 3 - Cyber Security Scenario Quiz",
    "class_slot": "October Week 5, 90-minute class",
    "description": "Students identify threats, choose protections, and justify selected answers using scenario evidence.",
    "activity_type": "structured-response",
    "assessment_purpose": "formal",
    "estimated_minutes": 30,
    "template_id": "worksheet",
    "teacher_note": "Use for Daily Grade #3 during the cyber security risk lesson.",
    "student_instructions": "Complete the scenario quiz and justify three answers with evidence from the scenario.",
    "student_output": "Scenario answers, protections, and three justification sentences.",
    "materials": "Cybersecurity notes, scenario cards or worksheet, and risk/protection vocabulary.",
    "fields": [{"id":"scenario_answers","type":"table-grid","prompt":"Record your scenario quiz answers.","rows":[{"id":"s1","text":"Scenario 1"},{"id":"s2","text":"Scenario 2"},{"id":"s3","text":"Scenario 3"},{"id":"s4","text":"Scenario 4"},{"id":"s5","text":"Scenario 5"},{"id":"s6","text":"Scenario 6"}],"columns":[{"id":"threat","text":"Threat"},{"id":"protection","text":"Best protection"}]},{"id":"justifications","type":"table-grid","prompt":"Justify three answers.","rows":[{"id":"j1","text":"Justification 1"},{"id":"j2","text":"Justification 2"},{"id":"j3","text":"Justification 3"}],"columns":[{"id":"scenario","text":"Scenario number"},{"id":"reason","text":"Reason"}]},{"id":"recommendation","type":"long-text","prompt":"Write one recommendation based on the highest-risk item."}]
  },
  {
    "id": "grade9_t3_daily_4_risk_map",
    "title": "G9 T3 Daily Grade 4 - Cybersecurity Risk Map",
    "class_slot": "October Week 7, 90-minute class",
    "description": "Students create a risk map with six risks, probability, impact, protection strategy, and priority recommendation.",
    "activity_type": "spreadsheet-table",
    "assessment_purpose": "formal",
    "estimated_minutes": 35,
    "template_id": "data-table",
    "teacher_note": "Use for Daily Grade #4 while students refine the STEM design plan.",
    "student_instructions": "Enter six risks, rate probability and impact, choose protection strategies, and write the priority recommendation.",
    "student_output": "Risk map table and priority recommendation paragraph.",
    "materials": "Cybersecurity notes, risk map practice, STEM project plan, and class examples.",
    "columns": [{"id":"risk","title":"Risk","type":"text","width":170},{"id":"probability","title":"Probability","type":"text","width":130},{"id":"impact","title":"Impact","type":"text","width":120},{"id":"protection","title":"Protection Strategy","type":"text","width":230}],
    "min_rows": 6,
    "max_rows": 8,
    "reflections": [{"id":"priority","prompt":"Which risk has the highest priority, and why?","required":true},{"id":"recommendation","prompt":"Write the protection recommendation paragraph.","required":true}]
  },
  {
    "id": "grade9_t3_daily_5_stem_project_proposal",
    "title": "G9 T3 Daily Grade 5 - STEM Project Proposal",
    "class_slot": "November Week 8, 90-minute class",
    "description": "Students create a STEM project proposal with problem, users, goal, tools/platforms, sketch or concept, materials, test criteria, and expected evidence.",
    "activity_type": "structured-response",
    "assessment_purpose": "formal",
    "estimated_minutes": 35,
    "template_id": "worksheet",
    "teacher_note": "Use for Daily Grade #5 before the STEM exam project begins.",
    "student_instructions": "Complete the STEM project proposal and record the result of one practice prototype feature.",
    "student_output": "STEM project proposal and practice prototype result.",
    "materials": "Project rubric, planning sheet, Tinkercad or Arduino/Freenove tools, project logbook, and approved resources.",
    "fields": [{"id":"problem","type":"long-text","prompt":"What problem will the STEM project address?"},{"id":"users_goal","type":"long-text","prompt":"Who are the users, and what is the project goal?"},{"id":"tools","type":"long-text","prompt":"Which tools or platforms will you use?"},{"id":"materials","type":"long-text","prompt":"List materials or files needed."},{"id":"tests","type":"table-grid","prompt":"Write 3 test criteria.","rows":[{"id":"test1","text":"Test criterion 1"},{"id":"test2","text":"Test criterion 2"},{"id":"test3","text":"Test criterion 3"}],"columns":[{"id":"criterion","text":"Criterion"},{"id":"evidence","text":"Expected evidence"}]},{"id":"prototype_result","type":"long-text","prompt":"What practice prototype feature did you test, and what happened?"}]
  },
  {
    "id": "grade9_t3_appreciation_1_digital_responsibility",
    "title": "G9 T3 Appreciation Grade 1 - Collaboration and Digital Responsibility",
    "class_slot": "October Week 4, 90-minute class",
    "description": "Students complete a collaboration and digital responsibility checklist and connect it to cyber safety habits.",
    "activity_type": "structured-response",
    "assessment_purpose": "formal",
    "estimated_minutes": 12,
    "template_id": "checklist",
    "teacher_note": "Use for Appreciation Grade #1 during the script kiddies and malware lesson.",
    "student_instructions": "Complete the checklist and explain one protection that would help a school user.",
    "student_output": "Digital responsibility checklist and protection note.",
    "materials": "Cybersecurity scenario notes, source care reminders, collaboration checklist, and class examples.",
    "fields": [{"id":"checklist","type":"checklist","prompt":"Collaboration and digital responsibility checklist","items":[{"id":"respect","text":"I communicated respectfully."},{"id":"sources","text":"I handled sources carefully."},{"id":"privacy","text":"I protected private information."},{"id":"participation","text":"I participated responsibly."},{"id":"account","text":"I followed safe account behavior."}]},{"id":"protection","type":"long-text","prompt":"What protection would help a school user, and why?"}]
  },
  {
    "id": "grade9_t3_appreciation_2_project_effort_organization",
    "title": "G9 T3 Appreciation Grade 2 - Project Effort and Organization",
    "class_slot": "November Week 9, 90-minute class",
    "description": "Students reflect on effort, organization, safe material use, perseverance, response to feedback, roles, and build schedule.",
    "activity_type": "structured-response",
    "assessment_purpose": "formal",
    "estimated_minutes": 12,
    "template_id": "reflection",
    "teacher_note": "Use for Appreciation Grade #2 during final STEM exam project planning.",
    "student_instructions": "Complete the project self-reflection and summarize the final exam task list and roles.",
    "student_output": "Project habits reflection and final plan notes.",
    "materials": "STEM proposal, logbook notes, feedback, project rubric, team roles, and build schedule.",
    "fields": [{"id":"effort","type":"rating-scale","prompt":"Rate your project effort from 1 to 5."},{"id":"organization","type":"long-text","prompt":"What evidence shows your files, notes, or materials are organized?"},{"id":"safe_use","type":"long-text","prompt":"How did you use materials or tools safely?"},{"id":"feedback","type":"long-text","prompt":"How did you respond to feedback or difficulty?"},{"id":"roles_schedule","type":"long-text","prompt":"Summarize team roles and the build schedule."}]
  },
  {
    "id": "grade9_t3_exam_stem_project_presentation",
    "title": "G9 T3 Exam Project - STEM Project Presentation",
    "class_slot": "November-December Weeks 10-12 exam project",
    "description": "Students submit final STEM project evidence with problem, tools, design choices, testing evidence, improvement, limitation, and reflection.",
    "activity_type": "external-artifact",
    "assessment_purpose": "formal",
    "estimated_minutes": 90,
    "template_id": "project-evidence",
    "evidence_mode": "either",
    "teacher_note": "Use as the exam project evidence wrapper for the STEM project presentation.",
    "student_instructions": "Submit final STEM project evidence and complete the reflection prompts.",
    "student_output": "Final STEM product evidence, logbook, and reflection.",
    "materials": "Prototype or digital product, project logbook, photos/screenshots, presentation notes, and rubric.",
    "checklist": [{"id":"problem","text":"The evidence explains the problem and users.","required":true},{"id":"design","text":"The evidence shows tools, materials, and design choices.","required":true},{"id":"testing","text":"The evidence includes testing results.","required":true},{"id":"improvement","text":"The evidence explains one improvement and limitation.","required":true},{"id":"reflection","text":"The final reflection is complete.","required":true}],
    "reflections": [{"id":"goal","prompt":"How does the project meet its goal?","required":true},{"id":"test","prompt":"What testing evidence is strongest?","required":true},{"id":"limitation","prompt":"What limitation remains?","required":true}]
  },
  {
    "id": "grade9_formative_t1_w1_device_system_sort",
    "title": "G9 T1 Practice - Input, Process, Output Device Sort",
    "class_slot": "March Week 1, 45-minute class",
    "description": "Students sort device parts into input, process, and output and justify one system response.",
    "activity_type": "card-sort",
    "assessment_purpose": "formative",
    "estimated_minutes": 15,
    "template_id": "category-sort",
    "teacher_note": "Use before the first system map and vocabulary work.",
    "student_instructions": "Sort each card into input, process, or output. Then explain one complete system response.",
    "student_output": "Sorted cards and one system response sentence.",
    "materials": "Class examples of automatic doors, motion lights, thermostats, phone sensors, and alarms.",
    "categories": [{"id":"input","title":"Input","helperText":"Detects or receives information."},{"id":"process","title":"Process","helperText":"Decides or runs instructions."},{"id":"output","title":"Output","helperText":"Shows, moves, sounds, or responds."}],
    "cards": [{"id":"motion_sensor","content":"Motion sensor"},{"id":"microcontroller","content":"Microcontroller or board"},{"id":"alarm_sound","content":"Alarm sound"},{"id":"button","content":"Button press"},{"id":"code_rule","content":"Code rule or condition"},{"id":"led_light","content":"LED light"},{"id":"temperature_reading","content":"Temperature reading"},{"id":"display_message","content":"Display message"}]
  },
  {
    "id": "grade9_formative_t1_w1_system_map",
    "title": "G9 T1 Practice - Physical Computing System Map",
    "class_slot": "March Week 1, 90-minute class",
    "description": "Students map input, process, output, state, and response for a simple electronic device.",
    "activity_type": "map-diagram",
    "assessment_purpose": "formative",
    "estimated_minutes": 20,
    "template_id": "labeled-map",
    "teacher_note": "Use after the core vocabulary table so students can apply the terms.",
    "student_instructions": "Create a system map for a simple electronic device with input, process, output, state, and response arrows.",
    "student_output": "Labeled system map and one decision sentence.",
    "materials": "System-map notes, example device, and class vocabulary."
  },
  {
    "id": "grade9_formative_t1_w2_digital_analog_sort",
    "title": "G9 T1 Practice - Digital and Analog Sort",
    "class_slot": "March Week 2, 45-minute class",
    "description": "Students classify examples as digital, analog, signal, or output to prepare for input-output diagrams.",
    "activity_type": "card-sort",
    "assessment_purpose": "formative",
    "estimated_minutes": 12,
    "template_id": "category-sort",
    "teacher_note": "Use during the light switch and volume knob comparison.",
    "student_instructions": "Sort the examples into the category that fits best.",
    "student_output": "Sorted signal examples.",
    "materials": "Week 2 vocabulary notes.",
    "categories": [{"id":"digital","title":"Digital","helperText":"Clear separate values, like on/off."},{"id":"analog","title":"Analog","helperText":"Smooth changing values."},{"id":"signal","title":"Signal","helperText":"A message or value sent in a system."},{"id":"output","title":"Output","helperText":"What the system produces."}],
    "cards": [{"id":"light_switch","content":"Light switch on/off"},{"id":"volume_knob","content":"Volume knob range"},{"id":"sensor_value","content":"Sensor value sent to a board"},{"id":"led_on","content":"LED turns on"},{"id":"button_pressed","content":"Button pressed or released"},{"id":"brightness_range","content":"Brightness changes smoothly"}]
  },
  {
    "id": "grade9_formative_t1_w2_physical_computing_diagram",
    "title": "G9 T1 Practice - Physical Computing Input-Output Diagram",
    "class_slot": "March Week 2, 45-minute class",
    "description": "Students diagram a physical computing system with two inputs, one process, two outputs, and reaction explanation.",
    "activity_type": "map-diagram",
    "assessment_purpose": "formative",
    "estimated_minutes": 18,
    "template_id": "labeled-map",
    "teacher_note": "Use before LED blink testing.",
    "student_instructions": "Create a diagram for a smart lamp, automatic door, classroom alarm, or another physical computing system.",
    "student_output": "Input-process-output diagram and two-sentence explanation.",
    "materials": "Class notes and example devices."
  },
  {
    "id": "grade9_formative_t1_w2_blink_delay_test_table",
    "title": "G9 T1 Practice - LED Blink Delay Test Table",
    "class_slot": "March Week 2, 90-minute class",
    "description": "Students record expected and actual LED behavior for three delay values.",
    "activity_type": "spreadsheet-table",
    "assessment_purpose": "formative",
    "estimated_minutes": 20,
    "template_id": "data-table",
    "teacher_note": "Use while students test the basic blink program.",
    "student_instructions": "Record the delay value, expected behavior, actual behavior, and conclusion for each test.",
    "student_output": "Delay test table and conclusion.",
    "materials": "Arduino IDE, blink program, LED circuit, and Serial/observation notes.",
    "columns": [{"id":"delay","title":"Delay Value (ms)","type":"number","width":140},{"id":"expected","title":"Expected Behavior","type":"text","width":190},{"id":"actual","title":"Actual Behavior","type":"text","width":190},{"id":"conclusion","title":"Conclusion","type":"text","width":200}],
    "min_rows": 3,
    "max_rows": 6,
    "reflections": [{"id":"effect","prompt":"How does delay change LED behavior?","required":true}]
  },
  {
    "id": "grade9_formative_t1_w3_lab_checklist_practice",
    "title": "G9 T1 Practice - Lab Safety Checklist Rehearsal",
    "class_slot": "March Week 3, 45-minute class",
    "description": "Students rehearse the lab safety checklist before the appreciation grade.",
    "activity_type": "structured-response",
    "assessment_purpose": "formative",
    "estimated_minutes": 10,
    "template_id": "checklist",
    "teacher_note": "Use before the graded safety and responsibility checklist.",
    "student_instructions": "Check the safety habits you used and choose one habit to improve next class.",
    "student_output": "Practice checklist and improvement goal.",
    "materials": "Lab safety rules and material-use expectations.",
    "fields": [{"id":"habits","type":"checklist","prompt":"Practice safety checklist","items":[{"id":"prepare","text":"I prepared materials."},{"id":"care","text":"I handled parts gently."},{"id":"power","text":"I connected power last."},{"id":"cleanup","text":"I cleaned up parts."}]},{"id":"goal","type":"short-text","prompt":"Which habit will you improve next class?"}]
  },
  {
    "id": "grade9_formative_t1_w3_instruction_trace_fix",
    "title": "G9 T1 Practice - Instruction Trace and Fix",
    "class_slot": "March Week 3, 90-minute class",
    "description": "Students trace program instruction order and identify one likely cause and fix.",
    "activity_type": "flowchart-algorithm",
    "assessment_purpose": "formative",
    "estimated_minutes": 15,
    "template_id": "sequence-algorithm",
    "teacher_note": "Use before students test and document the mini LED control circuit.",
    "student_instructions": "Build a short sequence showing the order of three program instructions and where a fix would happen.",
    "student_output": "Instruction sequence and fix point.",
    "materials": "LED control code, debugging notes, and circuit observation."
  },
  {
    "id": "grade9_formative_t1_w4_button_state_trace",
    "title": "G9 T1 Practice - Button State Trace",
    "class_slot": "March Week 4, 45-minute class",
    "description": "Students label button/input, board/process, LED/output, pin number, and pressed/released behavior.",
    "activity_type": "map-diagram",
    "assessment_purpose": "formative",
    "estimated_minutes": 18,
    "template_id": "labeled-map",
    "teacher_note": "Use before Daily Grade #2.",
    "student_instructions": "Trace the button-input system and label the input, process, output, pin number, and pressed/released behavior.",
    "student_output": "Labeled button-state trace.",
    "materials": "Button circuit example, state notes, and class diagram."
  },
  {
    "id": "grade9_formative_t1_w5_serial_monitor_values",
    "title": "G9 T1 Practice - Serial Monitor Values Worksheet",
    "class_slot": "April Week 5, 45-minute class",
    "description": "Students identify baud rate, data, message, output, and one debugging value from Serial Monitor.",
    "activity_type": "structured-response",
    "assessment_purpose": "formative",
    "estimated_minutes": 15,
    "template_id": "worksheet",
    "teacher_note": "Use while students run a program that sends text and sensor values.",
    "student_instructions": "Record one serial message and explain how it helps confirm the program is running.",
    "student_output": "Serial Monitor worksheet.",
    "materials": "Arduino IDE, Serial Monitor, sample program, and worksheet notes.",
    "fields": [{"id":"baud","type":"short-text","prompt":"What baud rate is used?"},{"id":"message","type":"long-text","prompt":"Record one serial message or value."},{"id":"debug","type":"long-text","prompt":"How could this data support debugging?"}]
  },
  {
    "id": "grade9_formative_t1_w5_potentiometer_reading_table",
    "title": "G9 T1 Practice - Potentiometer Reading Table",
    "class_slot": "April Week 5, 90-minute class",
    "description": "Students record potentiometer readings and LED brightness observations for low, medium, and high values.",
    "activity_type": "spreadsheet-table",
    "assessment_purpose": "formative",
    "estimated_minutes": 20,
    "template_id": "data-table",
    "teacher_note": "Use during analog input with potentiometer.",
    "student_instructions": "Record readings for low, medium, and high positions and explain which range gives reliable control.",
    "student_output": "Potentiometer value table and reliability note.",
    "materials": "Potentiometer setup, LED, Serial Monitor, and analog input notes.",
    "columns": [{"id":"position","title":"Position","type":"text","width":130},{"id":"reading","title":"Analog Reading","type":"number","width":140},{"id":"brightness","title":"LED Brightness","type":"text","width":160},{"id":"range","title":"Range Note","type":"text","width":190}],
    "min_rows": 3,
    "max_rows": 9,
    "reflections": [{"id":"reliable","prompt":"Which range gives the most reliable control, and why?","required":true}]
  },
  {
    "id": "grade9_formative_t1_w6_threshold_practice_table",
    "title": "G9 T1 Practice - Sensor Threshold Practice Table",
    "class_slot": "April Week 6, 45-minute class",
    "description": "Students practice reading sensor values, choosing a threshold, and predicting expected outputs.",
    "activity_type": "spreadsheet-table",
    "assessment_purpose": "formative",
    "estimated_minutes": 18,
    "template_id": "data-table",
    "teacher_note": "Use before Daily Grade #3.",
    "student_instructions": "Use sample readings to choose a threshold and predict outputs.",
    "student_output": "Threshold practice table.",
    "materials": "Sensor readings, threshold notes, and class examples.",
    "columns": [{"id":"reading","title":"Reading","type":"number","width":110},{"id":"prediction","title":"Expected Output","type":"text","width":170},{"id":"evidence","title":"Evidence","type":"text","width":210}],
    "seed_data": [[120,"",""],[450,"",""],[650,"",""],[900,"",""]],
    "min_rows": 4,
    "max_rows": 8,
    "reflections": [{"id":"threshold","prompt":"What threshold seems most reliable?","required":true}]
  },
  {
    "id": "grade9_formative_t1_w6_rgb_state_color_notes",
    "title": "G9 T1 Practice - RGB State Color Notes",
    "class_slot": "April Week 6, 90-minute class",
    "description": "Students plan RGB colors for ready, active, warning, and error states before programming.",
    "activity_type": "structured-response",
    "assessment_purpose": "formative",
    "estimated_minutes": 12,
    "template_id": "worksheet",
    "teacher_note": "Use with the simulator before the graded RGB state explanation.",
    "student_instructions": "Choose a color for each state and explain which color is clearest for an alert.",
    "student_output": "RGB state color notes.",
    "materials": "RGB simulator, state notes, and color vocabulary.",
    "fields": [{"id":"states","type":"table-grid","prompt":"Choose RGB state colors.","rows":[{"id":"ready","text":"Ready"},{"id":"active","text":"Active"},{"id":"warning","text":"Warning"},{"id":"error","text":"Error"}],"columns":[{"id":"color","text":"Color"},{"id":"reason","text":"Reason"}]},{"id":"alert","type":"short-text","prompt":"Which color is clearest for an alert?"}]
  },
  {
    "id": "grade9_formative_t1_w7_led_pattern_plan",
    "title": "G9 T1 Practice - Addressable LED Pattern Plan",
    "class_slot": "April Week 7, 45-minute class",
    "description": "Students sketch or map an addressable LED pattern with at least three color states and two speed settings.",
    "activity_type": "map-diagram",
    "assessment_purpose": "formative",
    "estimated_minutes": 18,
    "template_id": "labeled-map",
    "teacher_note": "Use during the addressable LED animation lesson.",
    "student_instructions": "Plan a light pattern and label each color state and speed setting.",
    "student_output": "LED pattern plan.",
    "materials": "Addressable LED notes, pattern examples, and color/speed vocabulary."
  },
  {
    "id": "grade9_formative_t1_w8_state_logic_practice_chart",
    "title": "G9 T1 Practice - State Logic Practice Chart",
    "class_slot": "April Week 8, 45-minute class",
    "description": "Students practice planning states, triggers, output responses, and explanation sentences before the graded chart.",
    "activity_type": "structured-response",
    "assessment_purpose": "formative",
    "estimated_minutes": 18,
    "template_id": "worksheet",
    "teacher_note": "Use before Daily Grade #4.",
    "student_instructions": "Complete the practice state logic chart and circle the hardest state to program.",
    "student_output": "Practice state logic chart.",
    "materials": "Ready, active, warning, and error state examples.",
    "fields": [{"id":"chart","type":"table-grid","prompt":"Practice state logic chart","rows":[{"id":"ready","text":"Ready"},{"id":"active","text":"Active"},{"id":"warning","text":"Warning"},{"id":"error","text":"Error"}],"columns":[{"id":"trigger","text":"Trigger"},{"id":"output","text":"Output response"},{"id":"sentence","text":"Explanation sentence"}]},{"id":"hardest","type":"long-text","prompt":"Which state seems hardest to program, and why?"}]
  },
  {
    "id": "grade9_formative_t1_w10_subsystem_test_log",
    "title": "G9 T1 Practice - Robotics Subsystem Test Log",
    "class_slot": "May Week 10, 90-minute class",
    "description": "Students document input reading, output response, code logic, and at least two subsystem test results.",
    "activity_type": "spreadsheet-table",
    "assessment_purpose": "formative",
    "estimated_minutes": 20,
    "template_id": "data-table",
    "teacher_note": "Use during exam project build sessions.",
    "student_instructions": "Record each subsystem tested, expected result, actual result, and evidence.",
    "student_output": "Subsystem test log.",
    "materials": "Robotics project, code, project log, photos/screenshots, and test notes.",
    "columns": [{"id":"subsystem","title":"Subsystem","type":"text","width":150},{"id":"expected","title":"Expected Result","type":"text","width":180},{"id":"actual","title":"Actual Result","type":"text","width":180},{"id":"evidence","title":"Evidence","type":"text","width":190}],
    "min_rows": 2,
    "max_rows": 8,
    "reflections": [{"id":"next","prompt":"What is the next build step?","required":true}]
  },
  {
    "id": "grade9_formative_t1_w11_reliability_test_table",
    "title": "G9 T1 Practice - Robotics Reliability Test Table",
    "class_slot": "May Week 11, 45-minute class",
    "description": "Students complete controlled testing with pass/fail results and fix notes.",
    "activity_type": "spreadsheet-table",
    "assessment_purpose": "formative",
    "estimated_minutes": 20,
    "template_id": "data-table",
    "teacher_note": "Use during exam project testing before improvement.",
    "student_instructions": "Record at least five controlled test attempts and choose one weak point to improve.",
    "student_output": "Reliability test table and weak point note.",
    "materials": "Robotics prototype, test-case table, project log, and code notes.",
    "columns": [{"id":"condition","title":"Test Condition","type":"text","width":170},{"id":"expected","title":"Expected","type":"text","width":150},{"id":"actual","title":"Actual","type":"text","width":150},{"id":"pass_fail","title":"Pass/Fail","type":"text","width":110},{"id":"fix","title":"Fix Note","type":"text","width":180}],
    "min_rows": 5,
    "max_rows": 10,
    "reflections": [{"id":"weak_point","prompt":"Which weak point should be improved first?","required":true}]
  },
  {
    "id": "grade9_formative_t2_w1_python_list_practice",
    "title": "G9 T2 Practice - Python List Data Practice",
    "class_slot": "June Week 1, 45-minute class",
    "description": "Students create a Python list, access items, change one item, append one item, and write index safety rules.",
    "activity_type": "structured-response",
    "assessment_purpose": "formative",
    "estimated_minutes": 18,
    "template_id": "worksheet",
    "teacher_note": "Use before the T2 vocabulary Word Hunt/daily grade.",
    "student_instructions": "Summarize your list practice and write two rules for using indexes safely.",
    "student_output": "List example and index safety rules.",
    "materials": "Python editor, class notes, and school-data examples.",
    "fields": [{"id":"list","type":"long-text","prompt":"What list did you create, and what changed?"},{"id":"access","type":"short-text","prompt":"Which items did you access?"},{"id":"rules","type":"long-text","prompt":"Write two rules for using list indexes safely."}]
  },
  {
    "id": "grade9_formative_t2_w2_while_loop_trace",
    "title": "G9 T2 Practice - While Loop Trace",
    "class_slot": "June Week 2, 45-minute class",
    "description": "Students trace a while loop and identify condition, repeated action, counter change, and stopping point.",
    "activity_type": "flowchart-algorithm",
    "assessment_purpose": "formative",
    "estimated_minutes": 15,
    "template_id": "sequence-algorithm",
    "teacher_note": "Use during while loop practice.",
    "student_instructions": "Create a loop trace that shows the condition, repeated action, counter change, and stopping point.",
    "student_output": "While loop trace.",
    "materials": "Loop example, Python notes, and trace table."
  },
  {
    "id": "grade9_formative_t2_w2_for_loop_filter_plan",
    "title": "G9 T2 Practice - For Loop Filter Plan",
    "class_slot": "June Week 2, 90-minute class",
    "description": "Students plan a for loop that counts, filters, or labels items in a list and tests two data sets.",
    "activity_type": "structured-response",
    "assessment_purpose": "formative",
    "estimated_minutes": 18,
    "template_id": "worksheet",
    "teacher_note": "Use while students compare for loops and while loops.",
    "student_instructions": "Describe the list, rule, two test data sets, and comparison between for and while loops.",
    "student_output": "For loop plan and test summary.",
    "materials": "Python editor, sample lists, and loop notes.",
    "fields": [{"id":"rule","type":"long-text","prompt":"What will your for loop count, filter, or label?"},{"id":"tests","type":"table-grid","prompt":"Plan two data set tests.","rows":[{"id":"set1","text":"Data set 1"},{"id":"set2","text":"Data set 2"}],"columns":[{"id":"data","text":"Data"},{"id":"expected","text":"Expected result"}]},{"id":"compare","type":"long-text","prompt":"Compare for loops and while loops in two sentences."}]
  },
  {
    "id": "grade9_formative_t2_w3_loop_error_practice",
    "title": "G9 T2 Practice - Loop Error Practice",
    "class_slot": "June Week 3, 45-minute class",
    "description": "Students practice correcting loop errors before the graded debugging check.",
    "activity_type": "structured-response",
    "assessment_purpose": "formative",
    "estimated_minutes": 15,
    "template_id": "worksheet",
    "teacher_note": "Use before Daily Grade #2.",
    "student_instructions": "Identify common loop errors and explain how to avoid one of them.",
    "student_output": "Loop error practice answers.",
    "materials": "Broken loop examples and debugging notes.",
    "fields": [{"id":"errors","type":"table-grid","prompt":"Practice loop errors","rows":[{"id":"colon","text":"Missing colon"},{"id":"indent","text":"Wrong indentation"},{"id":"never_stop","text":"Condition never stops"},{"id":"index","text":"Wrong list index"}],"columns":[{"id":"fix","text":"Fix"},{"id":"avoid","text":"How to avoid it"}]}]
  },
  {
    "id": "grade9_formative_t2_w3_string_data_checks",
    "title": "G9 T2 Practice - Strings as Data Checks",
    "class_slot": "June Week 3, 90-minute class",
    "description": "Students match string concepts with examples and summarize a string program that counts, searches, or checks a pattern.",
    "activity_type": "structured-response",
    "assessment_purpose": "formative",
    "estimated_minutes": 15,
    "template_id": "worksheet",
    "teacher_note": "Use after the loop debugging daily grade.",
    "student_instructions": "Match the string terms with examples and describe your strongest string example.",
    "student_output": "String concept check and program explanation.",
    "materials": "Python editor, string notes, and class examples.",
    "fields": [{"id":"terms","type":"table-grid","prompt":"Match string terms with examples.","rows":[{"id":"string","text":"String"},{"id":"character","text":"Character"},{"id":"index","text":"Index"},{"id":"length","text":"Length"},{"id":"substring","text":"Substring"}],"columns":[{"id":"example","text":"Example"}]},{"id":"program","type":"long-text","prompt":"What does your strongest string example check?"}]
  },
  {
    "id": "grade9_formative_t2_w4_data_info_decision_sort",
    "title": "G9 T2 Practice - Data, Information, Decision Sort",
    "class_slot": "June Week 4, 90-minute class",
    "description": "Students sort examples into data, information, and decision.",
    "activity_type": "card-sort",
    "assessment_purpose": "formative",
    "estimated_minutes": 12,
    "template_id": "category-sort",
    "teacher_note": "Use during the investigative cycle introduction.",
    "student_instructions": "Sort each card into data, information, or decision.",
    "student_output": "Sorted investigative cycle examples.",
    "materials": "Small dataset and data science notes.",
    "categories": [{"id":"data","title":"Data","helperText":"Raw values or answers."},{"id":"information","title":"Information","helperText":"Meaning found from data."},{"id":"decision","title":"Decision","helperText":"A choice made from evidence."}],
    "cards": [{"id":"survey_answers","content":"25 survey answers"},{"id":"average_minutes","content":"Average reading time is 18 minutes"},{"id":"add_reading_corner","content":"Create a quiet reading corner"},{"id":"temperature_values","content":"Temperature values by day"},{"id":"highest_category","content":"Sports was the most chosen option"},{"id":"change_schedule","content":"Change the practice schedule"}]
  },
  {
    "id": "grade9_formative_t2_w4_investigative_cycle_map",
    "title": "G9 T2 Practice - Investigative Cycle Map",
    "class_slot": "June Week 4, 90-minute class",
    "description": "Students identify problem, plan, data, analysis, and conclusion steps from the investigative cycle.",
    "activity_type": "map-diagram",
    "assessment_purpose": "formative",
    "estimated_minutes": 18,
    "template_id": "process-diagram",
    "teacher_note": "Use to bridge programming practice into data science work.",
    "student_instructions": "Map the investigative cycle for a school data question.",
    "student_output": "Investigative cycle map and one data question.",
    "materials": "Small dataset, data science notes, and school example questions."
  },
  {
    "id": "grade9_formative_t2_w5_measurable_question_draft",
    "title": "G9 T2 Practice - Measurable Data Question Draft",
    "class_slot": "July Week 5, 45-minute class",
    "description": "Students draft a measurable data question with survey items, data types, method, and privacy rule before the graded plan.",
    "activity_type": "structured-response",
    "assessment_purpose": "formative",
    "estimated_minutes": 18,
    "template_id": "worksheet",
    "teacher_note": "Use before Daily Grade #3.",
    "student_instructions": "Draft a measurable data question and underline one item that needs clearer wording.",
    "student_output": "Practice data collection plan draft.",
    "materials": "Collection plan examples and privacy notes.",
    "fields": [{"id":"question","type":"long-text","prompt":"Draft the measurable data question."},{"id":"items","type":"long-text","prompt":"List 5 survey or measurement items."},{"id":"privacy","type":"short-text","prompt":"What privacy rule will you follow?"},{"id":"revise","type":"short-text","prompt":"Which item needs clearer wording?"}]
  },
  {
    "id": "grade9_formative_t2_w6_messy_data_cleaning_table",
    "title": "G9 T2 Practice - Messy Data Cleaning Table",
    "class_slot": "July Week 6, 45-minute class",
    "description": "Students identify and correct blank cells, repeated answers, impossible numbers, spelling differences, or missing units.",
    "activity_type": "spreadsheet-table",
    "assessment_purpose": "formative",
    "estimated_minutes": 20,
    "template_id": "data-table",
    "teacher_note": "Use before the data teamwork appreciation grade.",
    "student_instructions": "Record messy data issues and explain why each cleaned value matters.",
    "student_output": "Data cleaning practice table.",
    "materials": "Assigned messy dataset and cleaning notes.",
    "columns": [{"id":"issue","title":"Issue Found","type":"text","width":170},{"id":"before","title":"Before","type":"text","width":130},{"id":"after","title":"After","type":"text","width":130},{"id":"reason","title":"Reason","type":"text","width":220}],
    "min_rows": 4,
    "max_rows": 10,
    "reflections": [{"id":"fair","prompt":"Why does one cleaned value matter for fair analysis?","required":true}]
  },
  {
    "id": "grade9_formative_t2_w6_tinkercad_data_model_evidence",
    "title": "G9 T2 Practice - Tinkercad Data Model Evidence",
    "class_slot": "July Week 6, 90-minute class",
    "description": "Students submit evidence of a simple Tinkercad model connected to one category, object, or display idea from the data topic.",
    "activity_type": "external-artifact",
    "assessment_purpose": "formative",
    "estimated_minutes": 20,
    "template_id": "project-evidence",
    "evidence_mode": "either",
    "teacher_note": "Use when Tinkercad is used to support the data topic.",
    "student_instructions": "Submit the model link or screenshot and explain how it connects to the data topic.",
    "student_output": "Tinkercad evidence and data connection note.",
    "materials": "Tinkercad access, dataset topic, screenshot or link tool.",
    "checklist": [{"id":"model","text":"The evidence shows a simple model or mock-up.","required":true},{"id":"connection","text":"The model connects to a data topic or category.","required":true}],
    "reflections": [{"id":"connection_note","prompt":"How does this model connect to the data topic?","required":true}]
  },
  {
    "id": "grade9_formative_t2_w7_chart_interpretation_practice",
    "title": "G9 T2 Practice - Chart Interpretation Draft",
    "class_slot": "July Week 7, 45-minute class",
    "description": "Students practice chart interpretation sentences before the graded chart check.",
    "activity_type": "spreadsheet-table",
    "assessment_purpose": "formative",
    "estimated_minutes": 18,
    "template_id": "data-table",
    "teacher_note": "Use before Daily Grade #4.",
    "student_instructions": "Enter practice chart data and draft one sentence for pattern, comparison, outlier or limitation, and conclusion.",
    "student_output": "Practice chart data and interpretation sentences.",
    "materials": "Dataset, chart examples, and interpretation notes.",
    "columns": [{"id":"item","title":"Item","type":"text","width":140},{"id":"value","title":"Value","type":"number","width":100},{"id":"note","title":"Evidence Note","type":"text","width":220}],
    "min_rows": 4,
    "max_rows": 10,
    "chart": {"enabled":true,"type":"bar","labelColumnId":"item","valueColumnId":"value"},
    "reflections": [{"id":"sentences","prompt":"Write your strongest evidence sentence.","required":true}]
  },
  {
    "id": "grade9_formative_t2_w7_outlier_correlation_sort",
    "title": "G9 T2 Practice - Outlier and Correlation Sort",
    "class_slot": "July Week 7, 90-minute class",
    "description": "Students sort sample findings into pattern, outlier, correlation, conclusion, or caution.",
    "activity_type": "card-sort",
    "assessment_purpose": "formative",
    "estimated_minutes": 12,
    "template_id": "category-sort",
    "teacher_note": "Use during correlation and outlier practice.",
    "student_instructions": "Sort each statement into the best data interpretation category.",
    "student_output": "Sorted interpretation cards.",
    "materials": "Sample points and chart notes.",
    "categories": [{"id":"pattern","title":"Pattern"},{"id":"outlier","title":"Outlier"},{"id":"correlation","title":"Correlation"},{"id":"conclusion","title":"Conclusion"},{"id":"caution","title":"Caution"}],
    "cards": [{"id":"most_values_rise","content":"Most values rise from Monday to Friday."},{"id":"one_value_far","content":"One value is far from the rest."},{"id":"two_values_change","content":"Two variables seem to increase together."},{"id":"evidence_supports","content":"The evidence supports this final idea."},{"id":"not_enough_data","content":"There is not enough data to prove cause."}]
  },
  {
    "id": "grade9_formative_t2_w8_data_report_practice",
    "title": "G9 T2 Practice - One-Page Data Report Practice",
    "class_slot": "July Week 8, 45-minute class",
    "description": "Students practice a one-page data report with title, question, chart, evidence, limitation, and recommendation.",
    "activity_type": "structured-response",
    "assessment_purpose": "formative",
    "estimated_minutes": 18,
    "template_id": "worksheet",
    "teacher_note": "Use before Daily Grade #5.",
    "student_instructions": "Draft the report sections and circle the sentence that uses the strongest evidence.",
    "student_output": "Practice report draft.",
    "materials": "Clean dataset, chart, and data report examples.",
    "fields": [{"id":"question","type":"long-text","prompt":"What question does the report answer?"},{"id":"evidence","type":"long-text","prompt":"Write three evidence statements."},{"id":"limitation","type":"long-text","prompt":"What limitation should the audience know?"},{"id":"recommendation","type":"long-text","prompt":"What recommendation follows from the evidence?"}]
  },
  {
    "id": "grade9_formative_t2_w10_clean_dataset_setup",
    "title": "G9 T2 Practice - Exam Project Clean Dataset Setup",
    "class_slot": "August Week 10, 45-minute class",
    "description": "Students finalize the dataset, clean remaining errors, and confirm chart title, labels, units, source, and limitation.",
    "activity_type": "spreadsheet-table",
    "assessment_purpose": "formative",
    "estimated_minutes": 20,
    "template_id": "data-table",
    "teacher_note": "Use at the start of the data exam project.",
    "student_instructions": "Record final dataset checks and the next build step.",
    "student_output": "Clean dataset setup checklist.",
    "materials": "Project plan, data table, chart tool, and source notes.",
    "columns": [{"id":"check","title":"Check","type":"text","width":160},{"id":"status","title":"Status","type":"text","width":110},{"id":"note","title":"Note","type":"text","width":220}],
    "seed_data": [["Clean remaining errors","",""],["Chart title","",""],["Labels and units","",""],["Source","",""],["Limitation","",""]],
    "min_rows": 5,
    "max_rows": 8,
    "reflections": [{"id":"next","prompt":"What is the next build step?","required":true}]
  },
  {
    "id": "grade9_formative_t2_w11_peer_feedback_clarity_check",
    "title": "G9 T2 Practice - Peer Feedback Clarity Check",
    "class_slot": "August Week 11, 45-minute class",
    "description": "Students test whether a peer can identify the main finding in 30 seconds and record one revision.",
    "activity_type": "structured-response",
    "assessment_purpose": "formative",
    "estimated_minutes": 12,
    "template_id": "reflection",
    "teacher_note": "Use during exam project testing and revision.",
    "student_instructions": "Ask one peer to identify the main finding and record the change you made from feedback.",
    "student_output": "Peer feedback clarity note.",
    "materials": "Data product draft, chart, peer feedback, and revision notes.",
    "fields": [{"id":"peer","type":"long-text","prompt":"What did the peer identify as the main finding?"},{"id":"change","type":"long-text","prompt":"What change did you make because of peer feedback?"}]
  },
  {
    "id": "grade9_formative_t2_w12_presentation_rehearsal_reflection",
    "title": "G9 T2 Practice - Data Presentation Rehearsal Reflection",
    "class_slot": "August Week 12, 45-minute class",
    "description": "Students rehearse the data project explanation and draft the final reflection.",
    "activity_type": "structured-response",
    "assessment_purpose": "formative",
    "estimated_minutes": 15,
    "template_id": "reflection",
    "teacher_note": "Use before the formal data project presentation.",
    "student_instructions": "Draft the presentation explanation and note one unclear visual to adjust.",
    "student_output": "Presentation rehearsal reflection.",
    "materials": "Final product, dataset, chart, rubric, and presentation checklist.",
    "fields": [{"id":"explanation","type":"long-text","prompt":"Summarize your 1-2 minute explanation."},{"id":"visual","type":"long-text","prompt":"What visual or link needs adjustment before presenting?"},{"id":"reflection","type":"long-text","prompt":"Draft the final reflection about data quality or limitations."}]
  },
  {
    "id": "grade9_formative_t3_w1_stem_media_idea_brainstorm",
    "title": "G9 T3 Practice - STEM Media Idea Brainstorm",
    "class_slot": "September Week 1, 45-minute class",
    "description": "Students connect one STEM project idea to image, sound, or sensor data.",
    "activity_type": "structured-response",
    "assessment_purpose": "formative",
    "estimated_minutes": 15,
    "template_id": "worksheet",
    "teacher_note": "Use before the T3 vocabulary Word Hunt/daily grade.",
    "student_instructions": "Brainstorm one STEM project idea and connect it to image, sound, or sensor data.",
    "student_output": "STEM idea and data connection.",
    "materials": "Project idea examples and digital media notes.",
    "fields": [{"id":"problem","type":"long-text","prompt":"What problem could the project help solve?"},{"id":"data_connection","type":"long-text","prompt":"How could image, sound, or sensor data support the idea?"}]
  },
  {
    "id": "grade9_formative_t3_w1_pixel_quality_tradeoff_table",
    "title": "G9 T3 Practice - Pixel Quality and File-Size Tradeoff",
    "class_slot": "September Week 1, 90-minute class",
    "description": "Students inspect pixel image examples and compare quality and file-size tradeoffs.",
    "activity_type": "spreadsheet-table",
    "assessment_purpose": "formative",
    "estimated_minutes": 18,
    "template_id": "data-table",
    "teacher_note": "Use after students complete the T3 vocabulary Word Hunt/daily grade.",
    "student_instructions": "Compare small image settings and add one image-representation note to the STEM logbook.",
    "student_output": "Pixel quality tradeoff table.",
    "materials": "Pixel image examples, RGB notes, and STEM logbook.",
    "columns": [{"id":"setting","title":"Image Setting","type":"text","width":150},{"id":"quality","title":"Quality","type":"text","width":130},{"id":"file_size","title":"File Size","type":"text","width":130},{"id":"tradeoff","title":"Tradeoff Note","type":"text","width":220}],
    "min_rows": 3,
    "max_rows": 8,
    "reflections": [{"id":"logbook","prompt":"Write one image-representation note for the STEM logbook.","required":true}]
  },
  {
    "id": "grade9_formative_t3_w2_representation_practice_check",
    "title": "G9 T3 Practice - Image and Sound Practice Check",
    "class_slot": "September Week 2, 45-minute class",
    "description": "Students practice image and sound representation questions before the graded check.",
    "activity_type": "structured-response",
    "assessment_purpose": "formative",
    "estimated_minutes": 18,
    "template_id": "worksheet",
    "teacher_note": "Use before Daily Grade #2.",
    "student_instructions": "Answer one image example and one sound example, then correct one answer using class notes.",
    "student_output": "Representation practice answers.",
    "materials": "Pixel, resolution, color depth, sample rate, sample size, quality, and compression notes.",
    "fields": [{"id":"image","type":"long-text","prompt":"Answer one image representation example."},{"id":"sound","type":"long-text","prompt":"Answer one sound representation example."},{"id":"correction","type":"long-text","prompt":"Which practice answer did you correct, and why?"}]
  },
  {
    "id": "grade9_formative_t3_w2_sound_evidence_table",
    "title": "G9 T3 Practice - Sound Setting Evidence Table",
    "class_slot": "September Week 2, 90-minute class",
    "description": "Students compare two sample rates or file settings using Audacity or an approved web audio tool.",
    "activity_type": "spreadsheet-table",
    "assessment_purpose": "formative",
    "estimated_minutes": 18,
    "template_id": "data-table",
    "teacher_note": "Use after Daily Grade #2 for the sound evidence progress check.",
    "student_instructions": "Record two sound settings and compare quality, file size, and evidence.",
    "student_output": "Sound evidence table.",
    "materials": "Audacity or approved web audio tool, headphones when available, and sound quality notes.",
    "columns": [{"id":"setting","title":"Sound Setting","type":"text","width":160},{"id":"quality","title":"Quality","type":"text","width":140},{"id":"file_size","title":"File Size","type":"text","width":120},{"id":"evidence","title":"Evidence","type":"text","width":220}],
    "min_rows": 2,
    "max_rows": 6,
    "reflections": [{"id":"choice","prompt":"Which setting would you choose for a school project, and why?","required":true}]
  },
  {
    "id": "grade9_formative_t3_w3_data_sensitivity_sort",
    "title": "G9 T3 Practice - Personal, Public, Sensitive Data Sort",
    "class_slot": "October Week 3, 45-minute class",
    "description": "Students sort examples into personal data, public data, and sensitive data.",
    "activity_type": "card-sort",
    "assessment_purpose": "formative",
    "estimated_minutes": 12,
    "template_id": "category-sort",
    "teacher_note": "Use at the start of the cybersecurity sequence.",
    "student_instructions": "Sort each example into personal, public, or sensitive data.",
    "student_output": "Sorted data examples and one personal data rule.",
    "materials": "Cybersecurity vocabulary notes and online-service examples.",
    "categories": [{"id":"personal","title":"Personal Data"},{"id":"public","title":"Public Data"},{"id":"sensitive","title":"Sensitive Data"}],
    "cards": [{"id":"name","content":"Name"},{"id":"school_event","content":"Public school event poster"},{"id":"password","content":"Password"},{"id":"location","content":"Live location"},{"id":"public_comment","content":"Public comment"},{"id":"school_email","content":"School email address"},{"id":"photo","content":"Student photo"},{"id":"homepage","content":"School homepage link"}]
  },
  {
    "id": "grade9_formative_t3_w3_online_service_scenarios",
    "title": "G9 T3 Practice - Online Service Scenario Analysis",
    "class_slot": "October Week 3, 45-minute class",
    "description": "Students analyze online-service scenarios for data collected, why it matters, and safer choice.",
    "activity_type": "structured-response",
    "assessment_purpose": "formative",
    "estimated_minutes": 18,
    "template_id": "worksheet",
    "teacher_note": "Use during personal data and privacy practice.",
    "student_instructions": "Analyze four online-service scenarios and write one personal data rule for project research.",
    "student_output": "Scenario analysis and personal data rule.",
    "materials": "Online-service scenarios and privacy notes.",
    "fields": [{"id":"scenarios","type":"table-grid","prompt":"Analyze four online-service scenarios.","rows":[{"id":"s1","text":"Scenario 1"},{"id":"s2","text":"Scenario 2"},{"id":"s3","text":"Scenario 3"},{"id":"s4","text":"Scenario 4"}],"columns":[{"id":"data","text":"Data collected"},{"id":"matter","text":"Why it matters"},{"id":"choice","text":"Safer choice"}]},{"id":"rule","type":"long-text","prompt":"Write one personal data rule for project research."}]
  },
  {
    "id": "grade9_formative_t3_w3_social_engineering_warning_signs",
    "title": "G9 T3 Practice - Social Engineering Warning Signs",
    "class_slot": "October Week 3, 90-minute class",
    "description": "Students match phishing, baiting, pretexting, urgency, and malware warning signs with examples.",
    "activity_type": "card-sort",
    "assessment_purpose": "formative",
    "estimated_minutes": 12,
    "template_id": "category-sort",
    "teacher_note": "Use before students rewrite an unsafe message into a safe response.",
    "student_instructions": "Sort each warning sign or example into the best social engineering category.",
    "student_output": "Sorted warning signs.",
    "materials": "Social engineering examples and cybersecurity notes.",
    "categories": [{"id":"phishing","title":"Phishing"},{"id":"baiting","title":"Baiting"},{"id":"pretexting","title":"Pretexting"},{"id":"urgency","title":"Urgency"},{"id":"malware","title":"Malware"}],
    "cards": [{"id":"password_request","content":"Message asks for your password"},{"id":"free_prize","content":"Free prize link"},{"id":"pretends_teacher","content":"Pretends to be a teacher or office account"},{"id":"act_now","content":"Act now or lose access"},{"id":"unsafe_download","content":"Unknown download attachment"}]
  },
  {
    "id": "grade9_formative_t3_w4_malware_comparison_chart",
    "title": "G9 T3 Practice - Malware Comparison Chart",
    "class_slot": "October Week 4, 90-minute class",
    "description": "Students compare cyber attack or malware case summaries and identify protections.",
    "activity_type": "spreadsheet-table",
    "assessment_purpose": "formative",
    "estimated_minutes": 20,
    "template_id": "data-table",
    "teacher_note": "Use after the digital responsibility appreciation checklist.",
    "student_instructions": "Compare malware or attack summaries and identify one protection for a school user.",
    "student_output": "Malware comparison chart.",
    "materials": "Case summaries, malware notes, and protection examples.",
    "columns": [{"id":"case","title":"Case or Malware Type","type":"text","width":170},{"id":"behavior","title":"Behavior","type":"text","width":190},{"id":"harm","title":"Possible Harm","type":"text","width":170},{"id":"protection","title":"Protection","type":"text","width":190}],
    "min_rows": 3,
    "max_rows": 8,
    "reflections": [{"id":"school_user","prompt":"Which protection would help a school user most?","required":true}]
  },
  {
    "id": "grade9_formative_t3_w5_security_practice_scenarios",
    "title": "G9 T3 Practice - Security Scenario Practice",
    "class_slot": "October Week 5, 45-minute class",
    "description": "Students practice identifying threats, choosing protections, and justifying answers before the graded scenario quiz.",
    "activity_type": "structured-response",
    "assessment_purpose": "formative",
    "estimated_minutes": 18,
    "template_id": "worksheet",
    "teacher_note": "Use before Daily Grade #3.",
    "student_instructions": "Practice three security scenarios and correct one uncertain answer using notes.",
    "student_output": "Practice scenario answers.",
    "materials": "Security scenario cards, threat vocabulary, and protection notes.",
    "fields": [{"id":"practice","type":"table-grid","prompt":"Practice three security scenarios.","rows":[{"id":"s1","text":"Scenario 1"},{"id":"s2","text":"Scenario 2"},{"id":"s3","text":"Scenario 3"}],"columns":[{"id":"threat","text":"Threat"},{"id":"protection","text":"Protection"},{"id":"reason","text":"Reason"}]},{"id":"correction","type":"long-text","prompt":"Which answer did you correct or confirm with notes?"}]
  },
  {
    "id": "grade9_formative_t3_w5_draft_risk_map",
    "title": "G9 T3 Practice - Draft Risk Map",
    "class_slot": "October Week 5, 90-minute class",
    "description": "Students compare security threats by probability and impact and draft a risk map.",
    "activity_type": "spreadsheet-table",
    "assessment_purpose": "formative",
    "estimated_minutes": 20,
    "template_id": "data-table",
    "teacher_note": "Use after the cyber security scenario quiz.",
    "student_instructions": "Place sample risks on a low/medium/high scale and write one recommendation.",
    "student_output": "Draft risk map and recommendation.",
    "materials": "Risk examples and probability/impact notes.",
    "columns": [{"id":"risk","title":"Risk","type":"text","width":170},{"id":"probability","title":"Probability","type":"text","width":130},{"id":"impact","title":"Impact","type":"text","width":120},{"id":"recommendation","title":"Recommendation","type":"text","width":220}],
    "min_rows": 3,
    "max_rows": 8,
    "reflections": [{"id":"highest","prompt":"Which item is highest risk, and why?","required":true}]
  },
  {
    "id": "grade9_formative_t3_w6_stem_problem_selection",
    "title": "G9 T3 Practice - STEM Problem Selection",
    "class_slot": "October Week 6, 45-minute class",
    "description": "Students choose a STEM project problem and identify users, constraints, possible data, and prototype tools.",
    "activity_type": "structured-response",
    "assessment_purpose": "formative",
    "estimated_minutes": 18,
    "template_id": "worksheet",
    "teacher_note": "Use to start STEM project planning after the cybersecurity lessons.",
    "student_instructions": "Choose a project problem and identify users, constraints, possible data, and prototype tools.",
    "student_output": "Problem statement and early project notes.",
    "materials": "Project examples, Tinkercad, Arduino/Freenove options, and planning sheet.",
    "fields": [{"id":"problem","type":"long-text","prompt":"Write the problem statement."},{"id":"users","type":"short-text","prompt":"Who are the users?"},{"id":"constraints","type":"long-text","prompt":"What constraints affect the project?"},{"id":"data","type":"long-text","prompt":"What data could support the project?"},{"id":"tools","type":"long-text","prompt":"Which prototype tools could work?"}]
  },
  {
    "id": "grade9_formative_t3_w6_first_stem_plan",
    "title": "G9 T3 Practice - First STEM Project Plan",
    "class_slot": "October Week 6, 90-minute class",
    "description": "Students create a first STEM project plan with goal, roles, materials, tools, sketch or concept, and three planned tests.",
    "activity_type": "structured-response",
    "assessment_purpose": "formative",
    "estimated_minutes": 22,
    "template_id": "worksheet",
    "teacher_note": "Use before the risk map final and STEM design refinement.",
    "student_instructions": "Complete the first project plan and update the logbook with one feedback note.",
    "student_output": "First STEM project plan.",
    "materials": "Project logbook, planning sheet, prototype tool access, and feedback notes.",
    "fields": [{"id":"goal","type":"long-text","prompt":"What is the project goal?"},{"id":"roles_materials","type":"long-text","prompt":"List roles and materials."},{"id":"tools","type":"long-text","prompt":"Which digital tools or platforms will you use?"},{"id":"tests","type":"table-grid","prompt":"Plan three tests.","rows":[{"id":"test1","text":"Test 1"},{"id":"test2","text":"Test 2"},{"id":"test3","text":"Test 3"}],"columns":[{"id":"question","text":"Test question"},{"id":"evidence","text":"Evidence expected"}]},{"id":"feedback","type":"long-text","prompt":"What feedback note did you add to the logbook?"}]
  },
  {
    "id": "grade9_formative_t3_w7_risk_map_practice",
    "title": "G9 T3 Practice - Risk Map Final Practice",
    "class_slot": "October Week 7, 45-minute class",
    "description": "Students practice a risk map with probability, impact, protection strategy, and priority recommendation before the graded map.",
    "activity_type": "spreadsheet-table",
    "assessment_purpose": "formative",
    "estimated_minutes": 18,
    "template_id": "data-table",
    "teacher_note": "Use before Daily Grade #4.",
    "student_instructions": "Practice risk mapping and underline the highest-priority risk.",
    "student_output": "Risk map practice table.",
    "materials": "Risk map examples and recommendation notes.",
    "columns": [{"id":"risk","title":"Risk","type":"text","width":170},{"id":"probability","title":"Probability","type":"text","width":130},{"id":"impact","title":"Impact","type":"text","width":120},{"id":"protection","title":"Protection Strategy","type":"text","width":220}],
    "min_rows": 4,
    "max_rows": 8,
    "reflections": [{"id":"priority","prompt":"Which practice risk has the highest priority?","required":true}]
  },
  {
    "id": "grade9_formative_t3_w7_proof_of_concept_evidence",
    "title": "G9 T3 Practice - STEM Proof of Concept Evidence",
    "class_slot": "October Week 7, 90-minute class",
    "description": "Students submit evidence of one proof of concept built with the approved project tool.",
    "activity_type": "external-artifact",
    "assessment_purpose": "formative",
    "estimated_minutes": 20,
    "template_id": "project-evidence",
    "evidence_mode": "either",
    "teacher_note": "Use after the risk map daily grade as the next build-step evidence.",
    "student_instructions": "Submit proof-of-concept evidence and write the next build step.",
    "student_output": "Proof-of-concept evidence and next build step.",
    "materials": "Approved project tool, Tinkercad or Arduino/Freenove materials, screenshots/photos, and logbook.",
    "checklist": [{"id":"approved_tool","text":"The evidence uses the approved project tool.","required":true},{"id":"proof","text":"The evidence shows a small test of the idea.","required":true}],
    "reflections": [{"id":"next_step","prompt":"What is the next build step?","required":true}]
  },
  {
    "id": "grade9_formative_t3_w10_build_log_first_feature",
    "title": "G9 T3 Practice - STEM First Feature Build Log",
    "class_slot": "November Week 10, 45-minute class",
    "description": "Students record the first exam project feature or model section with goal, tool, test condition, expected result, and actual result.",
    "activity_type": "structured-response",
    "assessment_purpose": "formative",
    "estimated_minutes": 18,
    "template_id": "worksheet",
    "teacher_note": "Use at the start of the STEM exam project.",
    "student_instructions": "Document the first feature or model section and write the next action.",
    "student_output": "First feature build log.",
    "materials": "Final project plan, logbook, prototype tools, and rubric.",
    "fields": [{"id":"feature","type":"long-text","prompt":"What first feature or model section did you build?"},{"id":"tool","type":"short-text","prompt":"What tool did you use?"},{"id":"test","type":"table-grid","prompt":"Record the first test.","rows":[{"id":"test1","text":"First test"}],"columns":[{"id":"condition","text":"Test condition"},{"id":"expected","text":"Expected result"},{"id":"actual","text":"Actual result"}]},{"id":"next","type":"short-text","prompt":"What is the next action?"}]
  },
  {
    "id": "grade9_formative_t3_w11_testing_improvement_table",
    "title": "G9 T3 Practice - STEM Testing and Improvement Table",
    "class_slot": "November Week 11, 45-minute class",
    "description": "Students complete controlled testing with three trials, identify one weakness, and record evidence for improvement.",
    "activity_type": "spreadsheet-table",
    "assessment_purpose": "formative",
    "estimated_minutes": 20,
    "template_id": "data-table",
    "teacher_note": "Use during exam project testing before the improvement session.",
    "student_instructions": "Record at least three controlled trials and choose one improvement for the next class.",
    "student_output": "Testing and improvement table.",
    "materials": "STEM prototype or digital product, test criteria, project logbook, and evidence files.",
    "columns": [{"id":"trial","title":"Trial","type":"text","width":100},{"id":"criteria","title":"Test Criteria","type":"text","width":160},{"id":"expected","title":"Expected","type":"text","width":150},{"id":"actual","title":"Actual","type":"text","width":150},{"id":"weakness","title":"Weakness/Evidence","type":"text","width":210}],
    "min_rows": 3,
    "max_rows": 8,
    "reflections": [{"id":"improvement","prompt":"Which improvement will you finish next?","required":true}]
  }
]
$grade9_app_activities$::jsonb) as activity (
        id text,
        title text,
        class_slot text,
        description text,
        activity_type text,
        assessment_purpose text,
        estimated_minutes integer,
        template_id text,
        evidence_mode text,
        teacher_note text,
        student_instructions text,
        student_output text,
        materials text,
        fields jsonb,
        categories jsonb,
        cards jsonb,
        columns jsonb,
        seed_data jsonb,
        min_rows integer,
        max_rows integer,
        chart jsonb,
        checklist jsonb,
        reflections jsonb
    )
),
grade9_prepared_activities as (
    select
        id,
        title,
        description || ' Slot: ' || class_slot || '.' as description,
        activity_type,
        assessment_purpose,
        estimated_minutes,
        'Use in ' || class_slot || '. ' || teacher_note as teacher_instructions,
        student_instructions,
        student_output,
        materials,
        case
            when activity_type = 'structured-response' then
                jsonb_build_object(
                    'templateId', coalesce(template_id, 'worksheet'),
                    'responseTemplate', jsonb_build_object(
                        'version', 1,
                        'templateId', coalesce(template_id, 'worksheet'),
                        'blocks', coalesce(
                            (
                                select jsonb_agg(
                                    jsonb_strip_nulls(jsonb_build_object(
                                        'id', coalesce(field->>'id', 'field_' || ordinality),
                                        'type', coalesce(field->>'type', 'short-text'),
                                        'prompt', coalesce(field->>'prompt', 'Respond to this prompt.'),
                                        'helperText', field->>'helperText',
                                        'required', coalesce((field->>'required')::boolean, true),
                                        'items', field->'items',
                                        'rows', field->'rows',
                                        'columns', field->'columns'
                                    ))
                                    order by ordinality
                                )
                                from jsonb_array_elements(coalesce(fields, '[]'::jsonb)) with ordinality as field_data(field, ordinality)
                            ),
                            jsonb_build_array(
                                jsonb_build_object('id', 'response', 'type', 'long-text', 'prompt', student_instructions, 'required', true)
                            )
                        )
                    )
                )
            when activity_type = 'card-sort' then
                jsonb_build_object(
                    'templateId', coalesce(template_id, 'category-sort'),
                    'cardSortTemplate', jsonb_build_object(
                        'version', 1,
                        'templateId', coalesce(template_id, 'category-sort'),
                        'prompt', student_instructions,
                        'helperText', 'Use class notes and the category names to decide where each card belongs.',
                        'requireAllCards', true,
                        'orderMode', case when coalesce(template_id, 'category-sort') in ('sequence-sort', 'process-sort') then 'within-categories' else 'none' end,
                        'categories', coalesce(categories, jsonb_build_array(jsonb_build_object('id', 'correct_order', 'title', 'Correct Order', 'helperText', 'First step at the top.'))),
                        'cards', coalesce(cards, '[]'::jsonb)
                    )
                )
            when activity_type = 'map-diagram' then
                jsonb_build_object(
                    'templateId', coalesce(template_id, 'blank-map-diagram'),
                    'excalidrawScene', null
                )
            when activity_type = 'spreadsheet-table' then
                jsonb_build_object(
                    'templateId', coalesce(template_id, 'data-table'),
                    'spreadsheetTemplate', jsonb_build_object(
                        'version', 1,
                        'templateId', coalesce(template_id, 'data-table'),
                        'columns', coalesce(columns, jsonb_build_array(
                            jsonb_build_object('id', 'item', 'title', 'Item', 'type', 'text', 'width', 150),
                            jsonb_build_object('id', 'value', 'title', 'Value', 'type', 'number', 'width', 120),
                            jsonb_build_object('id', 'notes', 'title', 'Notes', 'type', 'text', 'width', 200)
                        )),
                        'seedData', coalesce(seed_data, jsonb_build_array(
                            jsonb_build_array('', '', '', '', ''),
                            jsonb_build_array('', '', '', '', ''),
                            jsonb_build_array('', '', '', '', ''),
                            jsonb_build_array('', '', '', '', ''),
                            jsonb_build_array('', '', '', '', ''),
                            jsonb_build_array('', '', '', '', '')
                        )),
                        'minRows', coalesce(min_rows, 4),
                        'maxRows', coalesce(max_rows, 12),
                        'allowAddRows', true,
                        'chart', coalesce(chart, jsonb_build_object('enabled', false, 'type', 'bar', 'labelColumnId', 'item', 'valueColumnId', 'value')),
                        'reflectionPrompts', coalesce(reflections, jsonb_build_array(
                            jsonb_build_object('id', 'pattern', 'prompt', 'What pattern or result does your data show?', 'required', true)
                        ))
                    )
                )
            when activity_type = 'flowchart-algorithm' then
                jsonb_build_object('templateId', coalesce(template_id, 'sequence-algorithm'))
            when activity_type = 'external-artifact' then
                jsonb_build_object(
                    'templateId', coalesce(template_id, 'project-evidence'),
                    'externalArtifactTemplate', jsonb_build_object(
                        'version', 1,
                        'templateId', coalesce(template_id, 'project-evidence'),
                        'prompt', student_instructions,
                        'helperText', 'Submit evidence from the external tool, then complete the checklist and reflection prompts.',
                        'evidenceMode', coalesce(evidence_mode, 'either'),
                        'linkLabel', 'Project link',
                        'uploadLabel', 'Screenshot or PDF',
                        'allowedMimeTypes', jsonb_build_array('image/png', 'image/jpeg', 'image/webp', 'application/pdf'),
                        'checklistItems', coalesce(checklist, jsonb_build_array(
                            jsonb_build_object('id', 'matches_task', 'text', 'My evidence matches the assigned task.', 'required', true),
                            jsonb_build_object('id', 'readable', 'text', 'My evidence is readable or opens correctly.', 'required', true)
                        )),
                        'reflectionPrompts', coalesce(reflections, jsonb_build_array(
                            jsonb_build_object('id', 'created', 'prompt', 'What did you create or test?', 'required', true),
                            jsonb_build_object('id', 'improvement', 'prompt', 'What was one challenge or improvement?', 'required', true)
                        ))
                    )
                )
            else jsonb_build_object('templateId', 'worksheet')
        end as activity_data
    from grade9_raw_activities
)
insert into public.classroom_activities (
    id,
    title,
    description,
    activity_type,
    subject_slug,
    grades,
    teacher_instructions,
    student_instructions,
    materials,
    estimated_minutes,
    student_output,
    makeup_instructions,
    assessment_purpose,
    activity_data,
    owner_id,
    updated_at
)
select
    id,
    title,
    description,
    activity_type,
    'technology',
    array['9'],
    teacher_instructions,
    student_instructions,
    materials,
    estimated_minutes,
    student_output,
    case
        when assessment_purpose = 'formal'
            then 'Complete equivalent evidence independently using class notes, the project file, or teacher-approved screenshots. Submit before the teacher deadline.'
        else 'Complete the same formative activity independently using class notes and submit it before the next class.'
    end,
    assessment_purpose,
    activity_data,
    null,
    now()
from grade9_prepared_activities
on conflict (id) do update set
    title = excluded.title,
    description = excluded.description,
    activity_type = excluded.activity_type,
    subject_slug = excluded.subject_slug,
    grades = excluded.grades,
    teacher_instructions = excluded.teacher_instructions,
    student_instructions = excluded.student_instructions,
    materials = excluded.materials,
    estimated_minutes = excluded.estimated_minutes,
    student_output = excluded.student_output,
    makeup_instructions = excluded.makeup_instructions,
    assessment_purpose = excluded.assessment_purpose,
    activity_data = excluded.activity_data,
    updated_at = now();
