import { history } from "../../shared/content-helpers.js";

const code = `<div class="fm-code-card"><code>minutes = int(input("Minutes: "))<br>rate = 3<br>points = minutes * rate<br>print("Points:", points)</code></div>`;
const workshop = (id, short, title, summary, prompt, fields, minutes = 30, intro = "") => ({
  id, short, title, summary, minutes, kind: "choice", practiceMode: "production", prompt, fields, intro,
  items: fields.map((field, index) => ({
    title: `Activity ${index + 1}`,
    question: field.label,
    options: ["Run or trace the code and record exact evidence.", "Guess without running or tracing.", "Record only that it worked."],
    answer: 0,
    skill: "Produce code and test evidence",
    feedback: "The record includes code, input, output, or error evidence that another person can check.",
    retry: "Run or trace the stated task and record the exact line, value, output, or message requested.",
  })),
});

export const MODULE = {
  id: "MOD-PYTHON-FUNDAMENTALS-01", slug: "python-fundamentals", version: "0.1.0", storageKey: "mod-python-fundamentals-01-v0.1.0", mark: "PY", shortTitle: "Python fundamentals", title: "Python Input, Arithmetic, and Debugging", gradeLabel: "Grade 8 Technology", classes: ["8A", "8B"],
  sections: [
    { id: "start", short: "Start", title: "Read and run a small Python program", summary: "Learn the tools, vocabulary, time, and evidence for this module.", minutes: 7, html: `<section class="fm-opening"><div><p class="fm-label">Goal</p><h2>Follow the data before changing the code</h2><p>You will trace input, conversion, variables, arithmetic, and output. Then you will run short programs, read error messages, correct bugs, and record tests.</p><p><strong>Tools:</strong> this module and the Python editor assigned by your teacher. <strong>Evidence:</strong> three five-activity practice records, one calculator record, and an exported HTML report. Progress stays on this browser and device.</p></div>${code}</section><section class="fm-block"><p class="fm-label">Before you begin</p><h2>Four symbols matter</h2><p><code>=</code> stores a value. Parentheses hold the information passed to a function. Quotation marks surround text. <code>#</code> begins a comment that Python does not run.</p></section>` },
    { id: "arithmetic-learn", short: "Learn arithmetic", title: "Use input, variables, and arithmetic", summary: "Convert numeric input and calculate with named values.", minutes: 18, html: `<section class="fm-block"><p class="fm-label">Learn</p><h2>Each line changes what the program knows</h2>${code}<div class="fm-concept-grid"><div><h3>input()</h3><p>Pauses the program and receives text typed at the keyboard.</p></div><div><h3>int()</h3><p>Converts whole-number text such as <code>12</code> into an integer that Python can calculate with.</p></div><div><h3>Variable</h3><p>Gives a value a name. The current value is the most recent one assigned.</p></div><div><h3>print()</h3><p>Displays text, a value, or both.</p></div></div></section><section class="fm-block"><p class="fm-label">Inspect</p><h2>Trace the example with 12 minutes</h2><div class="fm-table-wrap"><table><thead><tr><th>After line</th><th><code>minutes</code></th><th><code>rate</code></th><th><code>points</code></th><th>Output</th></tr></thead><tbody><tr><td>1</td><td>12</td><td>not assigned</td><td>not assigned</td><td>none</td></tr><tr><td>2</td><td>12</td><td>3</td><td>not assigned</td><td>none</td></tr><tr><td>3</td><td>12</td><td>3</td><td>36</td><td>none</td></tr><tr><td>4</td><td>12</td><td>3</td><td>36</td><td>Points: 36</td></tr></tbody></table></div><p>Python evaluates the right side of an assignment first. In <code>score = score + 1</code>, it reads the old value, adds one, and stores the new value.</p></section>` },
    workshop("arithmetic-practice", "Practice arithmetic", "Run and trace five arithmetic tasks", "Use the assigned Python editor. Save the code and actual output for all five activities.", "Record five runs, not predictions", [
      { name: "activity1_input", label: "Activity 1 of 5. Write and run code that asks for a whole-number distance. Record the input line and one actual input.", type: "textarea", rows: 4, help: "Convert the keyboard text before calculating." },
      { name: "activity2_product", label: "Activity 2 of 5. Multiply that distance by 4. Record the assignment and actual result.", type: "textarea", rows: 4 },
      { name: "activity3_sum", label: "Activity 3 of 5. Add a fixed bonus of 10. Record the assignment and actual result.", type: "textarea", rows: 4 },
      { name: "activity4_division", label: "Activity 4 of 5. Divide the new total by 2. Record the assignment and actual result.", type: "textarea", rows: 4 },
      { name: "activity5_output", label: "Activity 5 of 5. Print each result with a clear label. Paste or type the exact output produced.", type: "textarea", rows: 6 },
    ], 35, `<section class="fm-block"><p class="fm-label">Practice file</p><h2>Create <code>distance_practice.py</code></h2><p>Build one line at a time. Run after each change. If a line fails, read the message before editing. Do not enter a phone number, student name, or other personal information.</p></section>`),
    { id: "debug-learn", short: "Learn errors", title: "Classify errors before fixing them", summary: "Separate syntax, name, type, and logic errors.", minutes: 18, html: `<section class="fm-block"><p class="fm-label">Learn</p><h2>The error type narrows the search</h2><div class="fm-concept-grid"><div><h3>Syntax error</h3><p>Python cannot read the structure, often because punctuation, indentation, or a keyword is wrong.</p></div><div><h3>Name error</h3><p>The program uses a variable or function name that has not been defined. Spelling and capitalization count.</p></div><div><h3>Type error</h3><p>An operation combines incompatible types, such as text and an integer.</p></div><div><h3>Logic error</h3><p>The program runs but the rule or operator gives the wrong result.</p></div></div></section><section class="fm-block"><p class="fm-label">Inspect</p><h2>Read the message, test one correction</h2><div class="fm-table-wrap"><table><thead><tr><th>Code or result</th><th>Evidence</th><th>First correction</th></tr></thead><tbody><tr><td><code>print("Total"</code></td><td>SyntaxError points near the line ending</td><td>Add the missing parenthesis</td></tr><tr><td><code>print(totl)</code></td><td>NameError says <code>totl</code> is not defined</td><td>Compare it with the defined name <code>total</code></td></tr><tr><td><code>age = input(...)</code>, then <code>age + 1</code></td><td>TypeError mentions <code>str</code> and <code>int</code></td><td>Convert the input with <code>int()</code></td></tr><tr><td>Price times quantity uses <code>+</code></td><td>Program runs but expected and actual totals differ</td><td>Replace <code>+</code> with <code>*</code></td></tr></tbody></table></div><p>Change one likely cause, run the same test, and keep the error and correction in the record.</p></section>` },
    workshop("debug-practice", "Practice debugging", "Correct and retest five Python errors", "Run each broken example in the assigned editor, make one correction, and record the evidence.", "Record five debugging cycles", [
      { name: "activity1_syntax", label: "Activity 1 of 5. Run print(\"Ready\". Record the error type, corrected line, and new output.", type: "textarea", rows: 5 },
      { name: "activity2_name", label: "Activity 2 of 5. Define total = 24, then run print(totl). Record the message and correction.", type: "textarea", rows: 5 },
      { name: "activity3_type", label: "Activity 3 of 5. Run age = input(\"Age: \") followed by next_age = age + 1. Correct it and record one passing test.", type: "textarea", rows: 6 },
      { name: "activity4_logic", label: "Activity 4 of 5. A program uses total = price + quantity. The rule is price times quantity. Correct it and compare expected with actual output.", type: "textarea", rows: 6 },
      { name: "activity5_indentation", label: "Activity 5 of 5. Run an if statement whose print line is not indented. Record the message, corrected code, and output.", type: "textarea", rows: 7 },
    ], 40, `<section class="fm-block"><p class="fm-label">Debug rule</p><h2>Keep the test stable</h2><p>For each activity, run the broken version first. Record the error type and useful line information. Make one correction and repeat the same input.</p></section>`),
    { id: "program-learn", short: "Plan a program", title: "Plan a calculator with input, process, and output", summary: "Turn a word problem into variables, calculations, labeled output, and tests.", minutes: 15, html: `<section class="fm-block"><p class="fm-label">Learn</p><h2>Plan the data path before typing</h2><div class="fm-table-wrap"><table><thead><tr><th>Input</th><th>Process</th><th>Output</th></tr></thead><tbody><tr><td><code>minutes</code>, whole number<br><code>rate</code>, fixed whole number</td><td><code>points = minutes * rate</code><br><code>bonus_points = points + 5</code><br><code>half = bonus_points / 2</code></td><td>Points, points with bonus, and half, each with a label</td></tr></tbody></table></div><p>Variable names should describe their values. Each output label should tell the reader what the number means.</p></section><section class="fm-block"><p class="fm-label">Inspect</p><h2>Choose tests before you code</h2><div class="fm-table-wrap"><table><thead><tr><th>Test</th><th>Input</th><th>Expected</th><th>Purpose</th></tr></thead><tbody><tr><td>Normal</td><td>12</td><td>36, 41, 20.5</td><td>Checks the main calculation path</td></tr><tr><td>Zero</td><td>0</td><td>0, 5, 2.5</td><td>Checks a boundary value</td></tr><tr><td>Another valid value</td><td>7</td><td>21, 26, 13</td><td>Checks that results change with input</td></tr></tbody></table></div></section>` },
    workshop("program-practice", "Practice programs", "Build and test a small calculator", "Create a complete file in the assigned Python editor and record five pieces of working evidence.", "Build the calculator in five activities", [
      { name: "activity1_plan", label: "Activity 1 of 5. For a school store calculator, name the required inputs, data types, and three outputs.", type: "textarea", rows: 5 },
      { name: "activity2_input", label: "Activity 2 of 5. Write and run the input and conversion lines for price and quantity.", type: "textarea", rows: 6 },
      { name: "activity3_process", label: "Activity 3 of 5. Write three calculation statements: subtotal, 7% tax, and final total.", type: "textarea", rows: 6 },
      { name: "activity4_output", label: "Activity 4 of 5. Write labeled print statements and record the exact output for price 2 and quantity 4.", type: "textarea", rows: 7 },
      { name: "activity5_tests", label: "Activity 5 of 5. Run two more tests. Record input, expected result, actual result, and pass or fail for each.", type: "textarea", rows: 8 },
    ], 45, `<section class="fm-block"><p class="fm-label">Practice file</p><h2>Create <code>store_calculator.py</code></h2><p>Use decimal input for price and whole-number input for quantity. The 7% tax formula is <code>tax = subtotal * 0.07</code>. Save the file after each successful run.</p></section>`),
    { id: "program-record", short: "Apply", title: "Create and test a Python calculator", summary: "Transfer the same data path to the calculator assigned by your teacher.", minutes: 35, kind: "form", prompt: "Record checkable Python evidence", intro: `<section class="fm-block"><p class="fm-label">Apply</p><h2>Submit working code and a repeatable test record</h2><p>Write and run the program in the assigned Python editor. Save the <code>.py</code> file. Use this record for the plan, exact code statements, outputs, test results, and correction history.</p></section>`, fields: [
      { name: "filename", label: "Python filename" },
      { name: "inputs", label: "Inputs, prompts, variable names, and required data types", type: "textarea", rows: 5 },
      { name: "calculations", label: "Three required calculation statements", type: "textarea", rows: 6 },
      { name: "outputs", label: "Labeled output statements and one exact output", type: "textarea", rows: 7 },
      { name: "tests", label: "Three test records with input, expected result, actual result, and pass or fail", type: "textarea", rows: 8 },
      { name: "debug", label: "One error message or failed result, the cause, exact correction, and retest result", type: "textarea", rows: 6 },
      { name: "file_location", label: "Saved file location or teacher-approved share link", type: "textarea", rows: 3, help: "Do not paste account passwords or private personal information." },
    ] },
    { id: "review", short: "Review", title: "Review the program and evidence", summary: "Check the code, tests, common mistakes, and next step.", minutes: 10, html: `<section class="fm-block"><p class="fm-label">Review</p><h2>Use this check before exporting</h2><ul><li>Numeric keyboard input is converted before arithmetic.</li><li>Every variable name matches exactly, including capitalization.</li><li>Each calculation uses the operator required by the problem.</li><li>Output labels explain what each number means.</li><li>Tests compare expected and actual results.</li><li>The saved <code>.py</code> file opens and runs.</li></ul><p><strong>Common mistakes:</strong> calculating with text, using <code>+</code> when the rule says multiply, and changing several lines before retesting.</p></section><section class="fm-block"><p class="fm-label">Next</p><h2>Export both forms of evidence</h2><p>Save the Python file and export the module report before changing computers. Your teacher may assign a separate graded program and rubric. Practice examples are not the formal assessment.</p></section>` },
    history,
  ],
};
