import { history } from "../../shared/content-helpers.js";

const flow = `<div class="fm-flow" role="img" aria-label="Home screen flows to report screen and then confirmation screen"><span>Home</span><b>→ tap Report</b><span>Report issue</span><b>→ tap Submit</b><span>Confirmation</span></div>`;

const workshop = (id, short, title, summary, prompt, fields, minutes = 25, intro = "") => ({
  id, short, title, summary, minutes, kind: "choice", practiceMode: "production", prompt, fields, intro,
  items: fields.map((field, index) => ({
    title: `Activity ${index + 1}`,
    question: field.label,
    options: ["Write a specific, checkable response.", "Write a vague opinion.", "Describe decoration instead of behavior."],
    answer: 0,
    skill: "Produce design evidence",
    feedback: "A specific response can be used to build or test the app.",
    retry: "Name the user action, app response, value, or measurable result requested.",
  })),
});

export const MODULE = {
  id: "MOD-APP-DESIGN-01", slug: "app-design", version: "0.1.0", storageKey: "mod-app-design-01-v0.1.0", mark: "A8", shortTitle: "App design", title: "App Screens, Events, and Test Cases", gradeLabel: "Grade 8 Technology", classes: ["8A", "8B"],
  sections: [
    { id: "start", short: "Start", title: "Plan an app before building it", summary: "Learn the vocabulary, tools, time, and evidence for this module.", minutes: 7, html: `<section class="fm-opening"><div><p class="fm-label">Goal</p><h2>Turn a real user problem into a plan another person can build</h2><p>You will define the user and problem, divide the app into screens, map events, and write tests. You need a computer and this browser. A drawing tool or paper is optional.</p><p><strong>Evidence:</strong> three five-activity practice records, one complete app plan, and an exported HTML report. Progress stays on this browser and device.</p></div>${flow}</section><section class="fm-block"><p class="fm-label">Before you begin</p><h2>Words you will use</h2><p><strong>User</strong> means the person completing a task. A <strong>screen</strong> is one app view. An <strong>interface element</strong> is a button, label, field, image, or list. An <strong>event</strong> is an action that makes the app respond. A <strong>test case</strong> checks one expected behavior.</p></section>` },
    { id: "user-learn", short: "Learn users", title: "Start with the user and problem", summary: "Connect an audience, need, feature, and success rule.", minutes: 15, html: `<section class="fm-block"><p class="fm-label">Learn</p><h2>A feature must solve part of the user's problem</h2><div class="fm-concept-grid"><div><h3>User</h3><p>Name a specific group. "Grade 8 students returning library books" is more useful than "everyone."</p></div><div><h3>Need</h3><p>State the difficulty before naming a solution. "Students forget due dates" is a need. "Add an alarm" is a feature.</p></div><div><h3>Feature</h3><p>Name an action the app performs to address the need.</p></div><div><h3>Success criterion</h3><p>Write a result another person can observe and test.</p></div></div></section><section class="fm-block"><p class="fm-label">Inspect</p><h2>Worked example: library reminder app</h2><div class="fm-table-wrap"><table><thead><tr><th>Decision</th><th>Specific plan</th><th>Why it works</th></tr></thead><tbody><tr><td>User and need</td><td>Students who borrow school books need a clear view of due dates.</td><td>It names a group and one difficulty.</td></tr><tr><td>Feature</td><td>Show current loans sorted by due date.</td><td>The action addresses the stated need.</td></tr><tr><td>Success</td><td>A student can find the next due book in two taps or fewer.</td><td>A tester can count the taps.</td></tr></tbody></table></div></section>` },
    workshop("user-practice", "Practice users", "Practice defining users and features", "Complete all five activities for a school event reminder app.", "Write five connected design decisions", [
      { name: "activity1_user", label: "Activity 1 of 5. Name a specific group of users and the school task they need to complete.", type: "textarea", rows: 3, help: "Use a group and a verb, such as students who need to..." },
      { name: "activity2_problem", label: "Activity 2 of 5. Write the problem without naming a button, screen, or other solution.", type: "textarea", rows: 3, help: "Describe what is difficult now." },
      { name: "activity3_feature", label: "Activity 3 of 5. Propose one feature that directly addresses the problem.", type: "textarea", rows: 3, help: "Start with a verb such as show, search, save, or remind." },
      { name: "activity4_success", label: "Activity 4 of 5. Write a measurable success criterion for that feature.", type: "textarea", rows: 3, help: "Use a visible result, time, tap count, or accuracy rule." },
      { name: "activity5_jobs", label: "Activity 5 of 5. Divide the app into at least three user jobs.", type: "textarea", rows: 4, help: "Each job should describe one action, not a screen color or decoration." },
    ], 25, `<section class="fm-block"><p class="fm-label">Scenario</p><h2>School event reminder</h2><p>Students miss club meetings and deadlines because details are spread across several messages. Design decisions must stay focused on finding an event and remembering what to do.</p></section>`),
    { id: "events-learn", short: "Learn events", title: "Connect screens with events", summary: "Map interface elements, user actions, app responses, and stored values.", minutes: 18, html: `<section class="fm-block"><p class="fm-label">Learn</p><h2>Each screen has one main job</h2>${flow}<div class="fm-concept-grid"><div><h3>Screen</h3><p>One app view with one main purpose.</p></div><div><h3>Interface element</h3><p>A visible control or piece of information, such as a button, label, input field, image, or list.</p></div><div><h3>Event</h3><p>A trigger and response. Example: when the user taps Submit, validate the form.</p></div><div><h3>Variable</h3><p>A named value the app stores or changes, such as <code>itemName</code>.</p></div></div></section><section class="fm-block"><p class="fm-label">Inspect</p><h2>Trace one complete path</h2><div class="fm-table-wrap"><table><thead><tr><th>Screen</th><th>User action</th><th>App response</th><th>Data used</th></tr></thead><tbody><tr><td>Home</td><td>Tap Report</td><td>Open Report issue</td><td>None</td></tr><tr><td>Report issue</td><td>Type item name</td><td>Store the text</td><td><code>itemName</code></td></tr><tr><td>Report issue</td><td>Tap Submit</td><td>Validate, save, open Confirmation</td><td><code>itemName</code></td></tr></tbody></table></div><p>A useful event map always names both sides: what the user does and what the app does next.</p></section>` },
    workshop("events-practice", "Practice events", "Practice a screen and event map", "Complete all five activities for a library seat reservation app.", "Build one connected interaction path", [
      { name: "activity1_screens", label: "Activity 1 of 5. Name three screens and write the one main job of each.", type: "textarea", rows: 5 },
      { name: "activity2_elements", label: "Activity 2 of 5. Place at least five interface elements on the correct screens.", type: "textarea", rows: 5, help: "Name the screen beside each button, label, field, or list." },
      { name: "activity3_events", label: "Activity 3 of 5. Write four event mappings in the form action → response.", type: "textarea", rows: 5 },
      { name: "activity4_data", label: "Activity 4 of 5. Name two values the app must store and explain when each changes.", type: "textarea", rows: 4 },
      { name: "activity5_feedback", label: "Activity 5 of 5. Write the confirmation or error feedback for one successful action and one failed action.", type: "textarea", rows: 4 },
    ], 30, `<section class="fm-block"><p class="fm-label">Scenario</p><h2>Library seat reservation</h2><p>A student chooses a date and time, selects an available seat, and submits a reservation. The app must stop blank or unavailable choices and confirm a successful reservation.</p></section>`),
    { id: "testing-learn", short: "Learn tests", title: "Write test cases before building", summary: "State the starting condition, action, expected result, and pass rule.", minutes: 15, html: `<section class="fm-block"><p class="fm-label">Learn</p><h2>A test case checks one path through the app</h2><p>A test case is not "try the app." It gives another tester enough detail to repeat the same check.</p><div class="fm-table-wrap"><table><thead><tr><th>Starting condition</th><th>Action</th><th>Expected result</th><th>Pass rule</th></tr></thead><tbody><tr><td>Home screen is open</td><td>Tap Report</td><td>Report screen opens</td><td>Correct screen opens once</td></tr><tr><td>Required name is blank</td><td>Tap Submit</td><td>Error names the missing field</td><td>No report is stored</td></tr><tr><td>All fields are valid</td><td>Tap Submit</td><td>Confirmation appears</td><td>Entered item name and report number are visible</td></tr></tbody></table></div></section><section class="fm-block"><p class="fm-label">Check your thinking</p><h2>Test normal use, mistakes, and boundaries</h2><p>A normal test follows the expected path. An invalid-input test checks how the app responds to missing or incorrect data. A boundary test checks a limit, such as the last available seat. After a correction, repeat the same test so the evidence is comparable.</p></section>` },
    workshop("testing-practice", "Practice tests", "Practice writing app test cases", "Complete five repeatable tests for a cafeteria preorder app.", "Write five test cases with expected results", [
      { name: "activity1_navigation", label: "Activity 1 of 5. Test that tapping Order opens the correct screen.", type: "textarea", rows: 4, help: "Include starting condition, action, expected result, and pass rule." },
      { name: "activity2_valid", label: "Activity 2 of 5. Test a complete order with valid choices.", type: "textarea", rows: 4 },
      { name: "activity3_missing", label: "Activity 3 of 5. Test one required field left blank.", type: "textarea", rows: 4 },
      { name: "activity4_boundary", label: "Activity 4 of 5. Test an item with zero portions remaining.", type: "textarea", rows: 4 },
      { name: "activity5_retest", label: "Activity 5 of 5. A blank order was saved by mistake. Write the test record you will repeat after the fix.", type: "textarea", rows: 5, help: "Record expected result, actual result, and pass or fail." },
    ], 30, `<section class="fm-block"><p class="fm-label">Scenario</p><h2>Cafeteria preorder</h2><p>The app lets students select one meal, choose a pickup time, and submit an order. It must not save incomplete orders or unavailable meals.</p></section>`),
    { id: "plan-record", short: "Apply", title: "Create a three-screen app plan", summary: "Transfer the ideas to an app problem assigned by your teacher.", minutes: 30, kind: "form", prompt: "Record a plan another student could build and test", intro: `<section class="fm-block"><p class="fm-label">Apply</p><h2>Use one connected idea</h2><p>Your user, problem, features, screens, events, data, and tests must describe the same app. Draw the screens in the assigned tool or on paper, then record the decisions here.</p></section>`, fields: [
      { name: "user", label: "User, problem, and measurable success criterion", type: "textarea", rows: 5 },
      { name: "screens", label: "At least three screens and the one main job of each", type: "textarea", rows: 6 },
      { name: "elements", label: "At least five interface elements and their screens", type: "textarea", rows: 6 },
      { name: "events", label: "At least four event mappings: action → response", type: "textarea", rows: 6 },
      { name: "data", label: "Inputs or variables, including what each stores and when it changes", type: "textarea", rows: 5 },
      { name: "tests", label: "Three test cases with starting condition, action, expected result, and pass rule", type: "textarea", rows: 7 },
    ] },
    { id: "review", short: "Review", title: "Review the app plan", summary: "Check vocabulary, connections, common mistakes, and the next step.", minutes: 10, html: `<section class="fm-block"><p class="fm-label">Review</p><h2>Use this check before exporting</h2><ul><li>The problem describes a user difficulty, not a screen or button.</li><li>Every feature addresses the stated problem.</li><li>Each screen has one main job.</li><li>Every event names the user action and app response.</li><li>Each test has an expected result that can pass or fail.</li></ul><p><strong>Common mistakes:</strong> designing decoration before behavior, storing data without naming it, and writing "works" as a test result.</p></section><section class="fm-block"><p class="fm-label">Next</p><h2>Export, then prototype</h2><p>Open History and export your saved report before changing computers. Your teacher may assign a separate prototype and rubric. This practice report is not the formal grade.</p></section>` },
    history,
  ],
};
