import { history, item, practice } from "../../shared/content-helpers.js";

const table = `<div class="fm-table-wrap"><table><caption>Club attendance</caption><thead><tr><th></th><th>A</th><th>B</th></tr></thead><tbody><tr><th>1</th><td>Club</td><td>Students</td></tr><tr><th>2</th><td>Art</td><td>18</td></tr><tr><th>3</th><td>Robotics</td><td>24</td></tr><tr><th>4</th><td>Science</td><td>21</td></tr><tr><th>5</th><td>Music</td><td>15</td></tr></tbody></table></div>`;

export const MODULE = {
  id: "MOD-SPREADSHEET-ANALYSIS-01", slug: "spreadsheet-analysis", version: "0.1.0", storageKey: "mod-spreadsheet-analysis-01-v0.1.0", mark: "D7", shortTitle: "Spreadsheet analysis", title: "Spreadsheet Formulas and Charts", gradeLabel: "Grade 7 Technology", classes: ["7A", "7B"],
  sections: [
    { id: "start", short: "Start", title: "Turn a table into evidence", summary: "Use cell references, functions, charts, sorting, and filtering to answer data questions.", minutes: 5, html: `<section class="fm-opening"><div><p class="fm-label">Goal</p><h2>Calculate first. Explain second.</h2><p>A spreadsheet is useful when its formulas and charts help you answer a specific question. You will work with school data and record what the results mean.</p></div>${table}</section><section class="fm-block"><p class="fm-label">Before you begin</p><h2>What you need and what you will save</h2><div class="fm-concept-grid"><div><h3>Know</h3><p>Rows, columns, cells, and cell references such as B2.</p></div><div><h3>Use</h3><p>A computer with Google Sheets, Excel, or another spreadsheet program.</p></div><div><h3>Save</h3><p>The working spreadsheet file or share link and this module's practice report.</p></div><div><h3>Submit</h3><p>Formulas, one labeled chart, and two conclusions that use exact values.</p></div></div></section>` },
    { id: "formula-learn", short: "Learn formulas", title: "Use cell references and functions", summary: "Review SUM, AVERAGE, MIN, MAX, arithmetic, and autofill.", minutes: 15, html: `<section class="fm-block"><p class="fm-label">Learn</p><h2>A formula uses cells, not copied answers</h2>${table}<div class="fm-concept-grid"><div><h3>=SUM(B2:B5)</h3><p>Adds all four values.</p></div><div><h3>=AVERAGE(B2:B5)</h3><p>Finds the mean.</p></div><div><h3>=MIN(B2:B5)</h3><p>Finds the lowest value.</p></div><div><h3>=MAX(B2:B5)</h3><p>Finds the highest value.</p></div></div><p class="fm-note">Every formula begins with <strong>=</strong>. The colon means every cell from the first reference through the last.</p></section>` },
    practice("formula-practice", "Formula practice", "Practice spreadsheet calculations", "Choose the formula or result that answers each question.", [
      item("Find the total", "Which formula adds B2 through B5?", ["=SUM(B2:B5)", "SUM B2-B5", "=B2:B5"], 0, "Write a SUM range", "The range B2:B5 includes all four attendance values.", "A spreadsheet formula starts with = and a range uses a colon."),
      item("Find the highest", "Which function finds the largest attendance value?", ["MIN", "MAX", "AVERAGE"], 1, "Choose MAX", "MAX returns the greatest number in the range.", "Think of the maximum value."),
      item("Find the lowest", "What does =MIN(B2:B5) return?", ["15", "24", "78"], 0, "Interpret MIN", "Music has the lowest value, 15.", "Look for the smallest value in column B."),
      item("Find the mean", "What is =AVERAGE(B2:B5)?", ["19.5", "21", "78"], 0, "Calculate an average", "The total is 78 and 78 ÷ 4 = 19.5.", "Add the values, then divide by four records."),
      item("Copy a formula", "You need the same calculation for the next row. Which tool is designed for this?", ["Autofill", "Sort", "Filter"], 0, "Use autofill", "Autofill copies a formula while adjusting its references.", "Choose the tool that extends a pattern."),
    ]),
    { id: "chart-learn", short: "Learn charts", title: "Match the chart to the question", summary: "Select data, choose a chart, add labels, and read the result.", minutes: 15, html: `<section class="fm-block"><p class="fm-label">Learn</p><h2>A chart needs a question</h2><div class="fm-concept-grid"><div><h3>Column or bar</h3><p>Compare categories.</p></div><div><h3>Line</h3><p>Show change over time.</p></div><div><h3>Pie</h3><p>Show parts of one whole.</p></div></div><ol class="fm-steps"><li><p>Select the category and value columns.</p></li><li><p>Insert the chart type that answers the question.</p></li><li><p>Add a title and axis labels.</p></li><li><p>Check that every value matches the table.</p></li></ol></section>` },
    practice("chart-practice", "Chart practice", "Practice chart decisions", "Choose the correct range, chart type, or interpretation.", [
      item("Compare clubs", "Which chart best compares attendance across four clubs?", ["Column chart", "Line chart", "Scatter plot"], 0, "Choose a comparison chart", "Columns make category values easy to compare.", "The club names are categories, not dates."),
      item("Select the range", "Which data must be selected for the club chart?", ["A1:B5", "Only B2", "Only A2:A5"], 0, "Select labels and values", "A1:B5 includes both headers, club names, and values.", "The chart needs category labels and numbers."),
      item("Name the chart", "Which title states exactly what the chart shows?", ["Chart 1", "Club Attendance", "My Data"], 1, "Write a specific title", "Club Attendance names the subject of the values.", "A reader should understand the chart without guessing."),
      item("Read the result", "Which club has the highest attendance?", ["Robotics", "Science", "Music"], 0, "Read a maximum from a chart", "Robotics has 24 students, the greatest value.", "Compare the four numbers in the source table."),
      item("Write evidence", "Which sentence is supported by the table?", ["Robotics has 9 more students than Music.", "Every club has the same attendance.", "Art has the highest attendance."], 0, "Write a supported conclusion", "24 minus 15 is 9, so the comparison is supported.", "Check each sentence against exact values."),
    ]),
    { id: "analysis-learn", short: "Analyze data", title: "Sort, filter, and check patterns", summary: "Change the view of the data without changing the records.", minutes: 12, html: `<section class="fm-block"><p class="fm-label">Learn</p><h2>Sorting rearranges. Filtering hides.</h2><div class="fm-concept-grid"><div><h3>Sort</h3><p>Places records in an order, such as highest to lowest.</p></div><div><h3>Filter</h3><p>Shows only records that match a rule.</p></div><div><h3>Conditional formatting</h3><p>Marks cells that meet a rule.</p></div><div><h3>COUNTIF</h3><p>Counts cells that match one condition.</p></div></div></section>` },
    practice("analysis-practice", "Analysis practice", "Practice sorting and filtering", "Decide which tool answers each data question.", [
      item("Rank values", "You want the clubs listed from highest attendance to lowest. What should you use?", ["Sort descending", "Filter", "Merge cells"], 0, "Sort descending", "Descending order places 24 before 21, 18, and 15.", "The task asks for a new order."),
      item("Show a subset", "You want to show only clubs with at least 20 students. What should you use?", ["Filter", "Delete rows", "Change the values"], 0, "Filter records", "A filter hides nonmatching records without deleting them.", "Keep the original data intact."),
      item("Highlight a rule", "You want values below 18 to appear with a warning color. What should you use?", ["Conditional formatting", "Autofill", "AVERAGE"], 0, "Use conditional formatting", "Conditional formatting changes the display when a rule is true.", "The value stays the same; only its appearance changes."),
      item("Count a category", "Which function counts cells that match one rule?", ["COUNTIF", "MAX", "SUM"], 0, "Choose COUNTIF", "COUNTIF counts matching entries.", "The function name includes both count and condition."),
      item("Protect the source", "After filtering, a row is hidden. What happened to the record?", ["It remains in the table", "It was deleted", "Its value became zero"], 0, "Separate hidden from deleted", "Filtering changes what is shown, not the stored record.", "A filter is reversible."),
    ]),
    { id: "analysis-record", short: "Record analysis", title: "Record a spreadsheet investigation", summary: "Plan one checkable spreadsheet file and conclusion.", minutes: 15, kind: "form", prompt: "Describe the file you built", intro: `<section class="fm-note"><strong>Required evidence:</strong> saved spreadsheet file, formulas, one chart, and written conclusions.</section>`, fields: [
      { name: "filename", label: "Spreadsheet filename" },
      { name: "question", label: "What data question did you investigate?", type: "textarea", rows: 2 },
      { name: "formulas", label: "Which formulas or functions did you use?", type: "textarea", rows: 2 },
      { name: "chart", label: "Which chart did you create, and why does it fit?", type: "textarea", rows: 3 },
      { name: "conclusion", label: "Write two conclusions supported by exact values.", type: "textarea", rows: 4 },
    ] },
    { id: "review", short: "Review", title: "Check the spreadsheet before you submit", summary: "Review the key ideas, catch common errors, and choose your next step.", minutes: 10, html: `<section class="fm-block"><p class="fm-label">Review</p><h2>Can another person check your result?</h2><ul class="fm-checklist"><li>The data has clear headers and consistent number formats.</li><li>Each formula begins with = and uses cell references.</li><li>The chart includes the correct categories, values, title, and labels.</li><li>Each conclusion names exact values from the spreadsheet.</li><li>The working file or share link opens on the computer.</li></ul></section><section class="fm-block"><p class="fm-label">Common mistakes</p><h2>Fix these before exporting</h2><div class="fm-concept-grid"><div><h3>Typed answer</h3><p>Replace a copied result such as 78 with a formula such as =SUM(B2:B5).</p></div><div><h3>Missing labels</h3><p>Select both category names and values before creating the chart.</p></div><div><h3>Unsupported claim</h3><p>Add the exact values that prove the conclusion.</p></div><div><h3>Lost file</h3><p>Give the file a clear name and confirm where it is saved.</p></div></div></section><section class="fm-note"><strong>Next:</strong> revisit any practice page that still feels uncertain. Then open History & export and download the report your teacher assigned.</section>` },
    history,
  ],
};
