export const ARCADE_MINUTE_SECONDS = 60;
export const FORMATIVE_PASS_SECONDS = 10 * ARCADE_MINUTE_SECONDS;
export const MAX_QUEUED_ARCADE_SECONDS = FORMATIVE_PASS_SECONDS;
export const FORMATIVE_PASS_MINUTES = FORMATIVE_PASS_SECONDS / ARCADE_MINUTE_SECONDS;
