const item = (title, question, options, answer, skill, feedback, retry, visual = "") => ({ title, question, options, answer, skill, feedback, retry, visual });
const practice = (id, short, title, summary, items, minutes = 20) => ({ id, short, title, summary, minutes, kind: "choice", items });
const flow = (input, program, output) => `<div class="fm-io-flow"><div><small>INPUT</small><br><b>${input}</b></div><span>→</span><div><small>PROGRAM</small><br><b>${program}</b></div><span>→</span><div><small>OUTPUT</small><br><b>${output}</b></div></div>`;

export const MODULE = {
  id: "MOD-MICROBIT-SENSING-01", slug: "microbit-sensing", version: "0.1.0", storageKey: "mod-microbit-sensing-01-v0.1.0", mark: "µB", shortTitle: "micro:bit lab", title: "micro:bit Inputs, Variables, and Sensors",
  sections: [
    { id: "start", short: "Start", title: "Make a micro:bit respond", summary: "Learn how a program receives information, makes a decision, and produces a result.", minutes: 5, html: `<section class="fm-opening"><div><p class="fm-label">Two builds</p><h2>Button counter, then automatic night light</h2><p>First, a button changes a number. Next, the light sensor controls the LED display. Both projects use the same input → program → output pattern.</p></div>${flow("button or sensor", "blocks and rules", "number or icon")}</section><section class="fm-note"><strong>Practice first.</strong> Build the fixed counter and night-light response in MakeCode when your teacher directs you.</section>` },
    { id: "board", short: "Meet the board", title: "Meet the micro:bit", summary: "Find the parts used by the two class builds.", minutes: 10, html: `<section class="fm-block"><p class="fm-label">Look</p><h2>The front of the board</h2><div class="fm-board-map"><div class="fm-board-button">A</div><div class="fm-led-grid" aria-label="Five by five LED display">${Array.from({length:25},(_,i)=>`<i class="${[2,6,7,8,10,11,12,13,14,16,17,18,22].includes(i)?"on":""}"></i>`).join("")}</div><div class="fm-board-button">B</div></div><div class="fm-concept-grid"><div><h3>Buttons A and B</h3><p>Inputs you press.</p></div><div><h3>LED display</h3><p>Output that shows numbers or icons.</p></div><div><h3>Light sensor</h3><p>Input measured through the LED display.</p></div><div><h3>USB connection</h3><p>Transfers the program and powers the board.</p></div></div></section>` },
    practice("parts-practice", "Parts practice", "Practice identifying parts", "Match each job to the correct micro:bit part.", [
      item("Press an input", "Which part can a student press to send an input?", ["Button A", "LED display", "USB cable only"], 0, "Identify a button input", "Button A is a physical input.", "Choose the part designed to be pressed."),
      item("Show a number", "Which part displays the counter value?", ["Battery pack", "LED display", "Button B"], 1, "Identify an output", "The LED grid can show a number.", "Look for the part that gives visible output."),
      item("Measure room light", "Which built-in input gives a light level from 0 to 255?", ["Light sensor", "Speaker", "Logo decoration"], 0, "Identify a sensor", "The light sensor produces the light-level input.", "A sensor measures the environment."),
      item("Transfer a program", "What connects the micro:bit to the computer for downloading a program?", ["USB cable", "Button A", "LED display"], 0, "Identify the USB connection", "The USB cable connects the board and computer.", "Choose the physical connection between devices."),
      item("Use the board safely", "Before unplugging the micro:bit, what should you check?", ["The program transfer has finished", "Every LED is on", "Button B is held"], 0, "Use safe transfer practice", "Wait for the transfer to finish before disconnecting.", "Avoid interrupting a file transfer.")
    ]),
    { id: "io-learn", short: "Learn I/O", title: "Understand input and output", summary: "Follow information from an action to a visible response.", minutes: 10, html: `<section class="fm-block"><p class="fm-label">Learn</p><h2>Input starts the action; output shows the result</h2>${flow("press button A", "add 1", "show the new number")}<p>An <strong>event</strong> tells the program when to run. The block <strong>on button A pressed</strong> is an event.</p><div class="fm-code-stack"><div class="fm-code-block event">on button A pressed</div><div class="fm-code-block variable">change count by 1</div><div class="fm-code-block output">show number count</div></div></section>` },
    practice("io-practice", "I/O practice", "Practice tracing input and output", "Decide what starts each program and what the user sees.", [
      item("Counter input", "In the counter, what is the input?", ["Pressing button A", "Showing the number", "The variable name"], 0, "Identify input", "The button press sends information into the program.", "Input is what the program receives."),
      item("Counter output", "In the counter, what is the output?", ["The number on the display", "Pressing button A", "The USB cable"], 0, "Identify output", "The displayed number is the result the user sees.", "Output comes from the program."),
      item("Find the event", "Which block says when the counter code should run?", ["on button A pressed", "show number", "change count"], 0, "Identify event", "The event waits for the button press.", "Look for the block that begins with when or on."),
      item("Trace the order", "Button A is pressed. What should happen next?", ["Change count, then show count", "Show count, then delete it", "Rotate the micro:bit"], 0, "Trace a program", "The program updates the value before displaying it.", "Follow the blocks from top to bottom."),
      item("Different input", "If the event changes to on button B pressed, what starts the program?", ["Button B", "Button A", "Light level"], 0, "Read an event", "The named event determines the input.", "Read the button named in the event block.")
    ]),
    { id: "variables-learn", short: "Learn variables", title: "Store a changing value", summary: "Use a variable to remember how many times a button was pressed.", minutes: 12, html: `<section class="fm-block"><p class="fm-label">Learn</p><h2>A variable is a named place that stores a value</h2><div class="fm-variable-demo"><span>name</span><strong>count</strong><span>current value</span><strong>0 → 1 → 2 → 3</strong></div><ol class="fm-steps"><li><p><strong>On start:</strong> set count to 0.</p></li><li><p><strong>On button A pressed:</strong> change count by 1.</p></li><li><p><strong>Then:</strong> show number count.</p></li></ol><p class="fm-note">The word <strong>count</strong> stays the same. The value stored in it changes.</p></section>` },
    practice("variables-practice", "Variable practice", "Practice tracing the counter", "Work out how the stored value changes.", [
      item("Start value", "The program sets count to 0 on start. What is stored before any press?", ["0", "1", "A"], 0, "Read initialization", "The set block gives count its first value: 0.", "Look at the on-start instruction."),
      item("One press", "count is 0. Button A changes count by 1. What is count now?", ["0", "1", "10"], 1, "Update a variable", "0 + 1 equals 1.", "Add the change to the current value."),
      item("Three presses", "count starts at 0 and button A is pressed three times. What is shown?", ["1", "2", "3"], 2, "Trace repeated events", "Each press adds one, so the display reaches 3.", "Count each button press."),
      item("Reset", "Which block returns the counter to its starting value?", ["set count to 0", "change count by 1", "show icon"], 0, "Reset a variable", "Setting count to 0 clears the previous count.", "Choose the block that replaces the stored value."),
      item("Use the name", "Why does show number count use the word count?", ["It displays the value stored in the variable", "It presses button A", "It measures light"], 0, "Use a variable value", "The block reads the current value stored under that name.", "The name points to stored information.")
    ]),
    { id: "conditions-learn", short: "Learn conditions", title: "Make a decision with a condition", summary: "Use if and else to choose one of two outputs.", minutes: 12, html: `<section class="fm-block"><p class="fm-label">Learn</p><h2>A condition asks a question that is true or false</h2>${flow("light level", "is it below 100?", "night icon or clear screen")}<div class="fm-code-stack"><div class="fm-code-block event">forever</div><div class="fm-code-block logic">if light level &lt; 100</div><div class="fm-code-block output">show night icon</div><div class="fm-code-block logic">else</div><div class="fm-code-block output">clear screen</div></div><p class="fm-note">The <strong>threshold</strong> is the comparison value. Here, the threshold is 100.</p></section>` },
    practice("conditions-practice", "Condition practice", "Practice conditions and thresholds", "Use the rule to predict the output.", [
      item("Below threshold", "Rule: if light level < 100, show the night icon. Light level is 60. What happens?", ["Show night icon", "Clear screen", "Add 1"], 0, "Test a below-threshold value", "60 is below 100, so the condition is true.", "Compare 60 with the threshold 100."),
      item("Above threshold", "Light level is 180. What happens with the same rule?", ["Show night icon", "Clear screen", "Press button A"], 1, "Use else", "180 is not below 100, so the else output runs.", "If the condition is false, follow else."),
      item("At threshold", "Light level is exactly 100. Is 100 below 100?", ["Yes", "No", "Only after a button press"], 1, "Read less than", "A value equal to 100 is not less than 100.", "Below does not include equal."),
      item("Change sensitivity", "You want the icon to appear in more lighting conditions. Which threshold could help?", ["150", "50", "0"], 0, "Adjust a threshold", "A higher threshold makes more light values count as below it.", "Test which choice includes more values."),
      item("Fixed response", "Why does the program include else?", ["To define what happens when the room is not dark", "To rename the variable", "To press the button"], 0, "Explain else", "Else gives a clear response when the condition is false.", "Both possible results need instructions.")
    ]),
    { id: "sensor-lab", short: "Sensor lab", title: "Test a light threshold", summary: "Change a simulated sensor value and watch the fixed night-light rule respond.", minutes: 15, kind: "sensor", lowOutput: { label: "Night icon shown — condition is true", icon: [2,6,10,15,21,22,23] }, highOutput: { label: "Display cleared — condition is false", icon: [] } },
    practice("debug-practice", "Debug practice", "Practice finding program mistakes", "Choose the smallest useful correction.", [
      item("Counter never changes", "The display always shows 0. The program has show number count but no change block. What is missing?", ["change count by 1", "clear screen", "light level"], 0, "Find a missing update", "The variable must change before a new number can appear.", "Find the block that updates count."),
      item("Wrong button", "The directions say button A, but only button B works. What should you inspect?", ["The event block", "The LED brightness", "The file name"], 0, "Inspect an event", "The event may name the wrong button.", "Check what starts the code."),
      item("Night icon in bright light", "The rule uses light level > 100 to show the night icon. What correction matches the plan?", ["Change > to <", "Delete forever", "Add to count"], 0, "Correct a comparison", "The icon should appear when light is below the threshold.", "Read the planned condition word: below."),
      item("Display never clears", "The icon appears in darkness but stays on in bright light. What is probably missing?", ["else: clear screen", "set count to 0", "button B pressed"], 0, "Complete both branches", "Else defines the bright-light output.", "What should happen when the condition is false?"),
      item("Good test", "Which test gives the clearest evidence that the threshold works?", ["Try one value below and one value above it", "Try the same value twice", "Change several blocks at once"], 0, "Test both branches", "Testing both sides shows whether each output runs.", "A condition has two possible results.")
    ]),
    { id: "counter-plan", short: "Counter record", title: "Build and test the button counter", summary: "Record the fixed counter build and its test evidence.", minutes: 20, kind: "form", prompt: "Record the counter test", intro: `<section class="fm-note"><strong>Fixed build:</strong> count starts at 0; button A adds 1; the display shows count. Button B may reset count to 0 after the required version works.</section>`, fields: [
      { name: "filename", label: "MakeCode file name" },
      { name: "prediction", label: "What should the display show after five presses? Explain.", type: "textarea", rows: 2 },
      { name: "result", label: "What did the display show after five presses?", type: "textarea", rows: 2 },
      { name: "fix", label: "What did you fix, or what did you check when it worked?", type: "textarea", rows: 3 }
    ] },
    { id: "night-plan", short: "Night-light record", title: "Build and test the night-light response", summary: "Record the threshold, two tests, and one evidence-based explanation.", minutes: 25, kind: "form", prompt: "Record the sensor test", intro: `<section class="fm-note"><strong>Fixed build:</strong> if light level is below the chosen threshold, show the night icon; otherwise clear the display.</section>`, fields: [
      { name: "threshold", label: "Threshold used", type: "number", min: "1", help: "Use a value from 1 to 254." },
      { name: "below", label: "Test below the threshold: value and output", type: "textarea", rows: 2 },
      { name: "above", label: "Test above the threshold: value and output", type: "textarea", rows: 2 },
      { name: "explanation", label: "Explain how the input, condition, and output work together", type: "textarea", rows: 4 }
    ] },
    { id: "history", short: "History & export", title: "Review and export your practice", summary: "Recreate saved attempts and download one practice report.", minutes: 10, kind: "review" }
  ]
};
